// Code generated by MockGen. DO NOT EDIT.
// Source: internal/auth/processor/auth.go
//
// Generated by this command:
//
//	mockgen -source=internal/auth/processor/auth.go -destination=internal/auth/processor/mocks_test.go -package=processor
//

// Package processor is a generated GoMock package.
package processor

import (
	googleoauth "base-server/internal/clients/googleoauth"
	store "base-server/internal/store"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthStore is a mock of AuthStore interface.
type MockAuthStore struct {
	ctrl     *gomock.Controller
	recorder *MockAuthStoreMockRecorder
	isgomock struct{}
}

// MockAuthStoreMockRecorder is the mock recorder for MockAuthStore.
type MockAuthStoreMockRecorder struct {
	mock *MockAuthStore
}

// NewMockAuthStore creates a new mock instance.
func NewMockAuthStore(ctrl *gomock.Controller) *MockAuthStore {
	mock := &MockAuthStore{ctrl: ctrl}
	mock.recorder = &MockAuthStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthStore) EXPECT() *MockAuthStoreMockRecorder {
	return m.recorder
}

// CheckIfEmailExists mocks base method.
func (m *MockAuthStore) CheckIfEmailExists(ctx context.Context, email string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckIfEmailExists", ctx, email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckIfEmailExists indicates an expected call of CheckIfEmailExists.
func (mr *MockAuthStoreMockRecorder) CheckIfEmailExists(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckIfEmailExists", reflect.TypeOf((*MockAuthStore)(nil).CheckIfEmailExists), ctx, email)
}

// CreateUserOnEmailSignup mocks base method.
func (m *MockAuthStore) CreateUserOnEmailSignup(ctx context.Context, firstName, lastName, email, hashedPassword string) (store.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserOnEmailSignup", ctx, firstName, lastName, email, hashedPassword)
	ret0, _ := ret[0].(store.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserOnEmailSignup indicates an expected call of CreateUserOnEmailSignup.
func (mr *MockAuthStoreMockRecorder) CreateUserOnEmailSignup(ctx, firstName, lastName, email, hashedPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserOnEmailSignup", reflect.TypeOf((*MockAuthStore)(nil).CreateUserOnEmailSignup), ctx, firstName, lastName, email, hashedPassword)
}

// CreateUserOnGoogleSignIn mocks base method.
func (m *MockAuthStore) CreateUserOnGoogleSignIn(ctx context.Context, googleUserId, email, firstName, lastName string) (store.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserOnGoogleSignIn", ctx, googleUserId, email, firstName, lastName)
	ret0, _ := ret[0].(store.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserOnGoogleSignIn indicates an expected call of CreateUserOnGoogleSignIn.
func (mr *MockAuthStoreMockRecorder) CreateUserOnGoogleSignIn(ctx, googleUserId, email, firstName, lastName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserOnGoogleSignIn", reflect.TypeOf((*MockAuthStore)(nil).CreateUserOnGoogleSignIn), ctx, googleUserId, email, firstName, lastName)
}

// GetCredentialsByEmail mocks base method.
func (m *MockAuthStore) GetCredentialsByEmail(ctx context.Context, email string) (store.EmailAuth, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCredentialsByEmail", ctx, email)
	ret0, _ := ret[0].(store.EmailAuth)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCredentialsByEmail indicates an expected call of GetCredentialsByEmail.
func (mr *MockAuthStoreMockRecorder) GetCredentialsByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCredentialsByEmail", reflect.TypeOf((*MockAuthStore)(nil).GetCredentialsByEmail), ctx, email)
}

// GetOauthUserByEmail mocks base method.
func (m *MockAuthStore) GetOauthUserByEmail(ctx context.Context, email string) (store.OauthAuth, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOauthUserByEmail", ctx, email)
	ret0, _ := ret[0].(store.OauthAuth)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOauthUserByEmail indicates an expected call of GetOauthUserByEmail.
func (mr *MockAuthStoreMockRecorder) GetOauthUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOauthUserByEmail", reflect.TypeOf((*MockAuthStore)(nil).GetOauthUserByEmail), ctx, email)
}

// GetUserByAuthID mocks base method.
func (m *MockAuthStore) GetUserByAuthID(ctx context.Context, authID uuid.UUID) (store.AuthenticatedUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByAuthID", ctx, authID)
	ret0, _ := ret[0].(store.AuthenticatedUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByAuthID indicates an expected call of GetUserByAuthID.
func (mr *MockAuthStoreMockRecorder) GetUserByAuthID(ctx, authID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByAuthID", reflect.TypeOf((*MockAuthStore)(nil).GetUserByAuthID), ctx, authID)
}

// GetUserByExternalID mocks base method.
func (m *MockAuthStore) GetUserByExternalID(ctx context.Context, externalID uuid.UUID) (store.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByExternalID", ctx, externalID)
	ret0, _ := ret[0].(store.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByExternalID indicates an expected call of GetUserByExternalID.
func (mr *MockAuthStoreMockRecorder) GetUserByExternalID(ctx, externalID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByExternalID", reflect.TypeOf((*MockAuthStore)(nil).GetUserByExternalID), ctx, externalID)
}

// UpdateStripeCustomerIDByUserID mocks base method.
func (m *MockAuthStore) UpdateStripeCustomerIDByUserID(ctx context.Context, userID uuid.UUID, stripeCustomerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStripeCustomerIDByUserID", ctx, userID, stripeCustomerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStripeCustomerIDByUserID indicates an expected call of UpdateStripeCustomerIDByUserID.
func (mr *MockAuthStoreMockRecorder) UpdateStripeCustomerIDByUserID(ctx, userID, stripeCustomerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStripeCustomerIDByUserID", reflect.TypeOf((*MockAuthStore)(nil).UpdateStripeCustomerIDByUserID), ctx, userID, stripeCustomerID)
}

// MockBillingProcessor is a mock of BillingProcessor interface.
type MockBillingProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockBillingProcessorMockRecorder
	isgomock struct{}
}

// MockBillingProcessorMockRecorder is the mock recorder for MockBillingProcessor.
type MockBillingProcessorMockRecorder struct {
	mock *MockBillingProcessor
}

// NewMockBillingProcessor creates a new mock instance.
func NewMockBillingProcessor(ctrl *gomock.Controller) *MockBillingProcessor {
	mock := &MockBillingProcessor{ctrl: ctrl}
	mock.recorder = &MockBillingProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBillingProcessor) EXPECT() *MockBillingProcessorMockRecorder {
	return m.recorder
}

// CreateStripeCustomer mocks base method.
func (m *MockBillingProcessor) CreateStripeCustomer(ctx context.Context, email string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStripeCustomer", ctx, email)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStripeCustomer indicates an expected call of CreateStripeCustomer.
func (mr *MockBillingProcessorMockRecorder) CreateStripeCustomer(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStripeCustomer", reflect.TypeOf((*MockBillingProcessor)(nil).CreateStripeCustomer), ctx, email)
}

// MockGoogleOAuthClient is a mock of GoogleOAuthClient interface.
type MockGoogleOAuthClient struct {
	ctrl     *gomock.Controller
	recorder *MockGoogleOAuthClientMockRecorder
	isgomock struct{}
}

// MockGoogleOAuthClientMockRecorder is the mock recorder for MockGoogleOAuthClient.
type MockGoogleOAuthClientMockRecorder struct {
	mock *MockGoogleOAuthClient
}

// NewMockGoogleOAuthClient creates a new mock instance.
func NewMockGoogleOAuthClient(ctrl *gomock.Controller) *MockGoogleOAuthClient {
	mock := &MockGoogleOAuthClient{ctrl: ctrl}
	mock.recorder = &MockGoogleOAuthClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGoogleOAuthClient) EXPECT() *MockGoogleOAuthClientMockRecorder {
	return m.recorder
}

// GetAccessToken mocks base method.
func (m *MockGoogleOAuthClient) GetAccessToken(ctx context.Context, code string) (googleoauth.GoogleOauthTokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessToken", ctx, code)
	ret0, _ := ret[0].(googleoauth.GoogleOauthTokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccessToken indicates an expected call of GetAccessToken.
func (mr *MockGoogleOAuthClientMockRecorder) GetAccessToken(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessToken", reflect.TypeOf((*MockGoogleOAuthClient)(nil).GetAccessToken), ctx, code)
}

// GetUserInfo mocks base method.
func (m *MockGoogleOAuthClient) GetUserInfo(ctx context.Context, token string) (googleoauth.UserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserInfo", ctx, token)
	ret0, _ := ret[0].(googleoauth.UserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserInfo indicates an expected call of GetUserInfo.
func (mr *MockGoogleOAuthClientMockRecorder) GetUserInfo(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInfo", reflect.TypeOf((*MockGoogleOAuthClient)(nil).GetUserInfo), ctx, token)
}

// MockEmailService is a mock of EmailService interface.
type MockEmailService struct {
	ctrl     *gomock.Controller
	recorder *MockEmailServiceMockRecorder
	isgomock struct{}
}

// MockEmailServiceMockRecorder is the mock recorder for MockEmailService.
type MockEmailServiceMockRecorder struct {
	mock *MockEmailService
}

// NewMockEmailService creates a new mock instance.
func NewMockEmailService(ctrl *gomock.Controller) *MockEmailService {
	mock := &MockEmailService{ctrl: ctrl}
	mock.recorder = &MockEmailServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailService) EXPECT() *MockEmailServiceMockRecorder {
	return m.recorder
}

// SendEmail mocks base method.
func (m *MockEmailService) SendEmail(ctx context.Context, to, subject, htmlContent string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEmail", ctx, to, subject, htmlContent)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendEmail indicates an expected call of SendEmail.
func (mr *MockEmailServiceMockRecorder) SendEmail(ctx, to, subject, htmlContent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmail", reflect.TypeOf((*MockEmailService)(nil).SendEmail), ctx, to, subject, htmlContent)
}
