// Code generated by MockGen. DO NOT EDIT.
// Source: processor.go
//
// Generated by this command:
//
//	mockgen -source=processor.go -destination=mocks_test.go -package=processor
//

// Package processor is a generated GoMock package.
package processor

import (
	store "base-server/internal/store"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockCampaignStore is a mock of CampaignStore interface.
type MockCampaignStore struct {
	ctrl     *gomock.Controller
	recorder *MockCampaignStoreMockRecorder
	isgomock struct{}
}

// MockCampaignStoreMockRecorder is the mock recorder for MockCampaignStore.
type MockCampaignStoreMockRecorder struct {
	mock *MockCampaignStore
}

// NewMockCampaignStore creates a new mock instance.
func NewMockCampaignStore(ctrl *gomock.Controller) *MockCampaignStore {
	mock := &MockCampaignStore{ctrl: ctrl}
	mock.recorder = &MockCampaignStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCampaignStore) EXPECT() *MockCampaignStoreMockRecorder {
	return m.recorder
}

// CreateCampaign mocks base method.
func (m *MockCampaignStore) CreateCampaign(ctx context.Context, params store.CreateCampaignParams) (store.Campaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCampaign", ctx, params)
	ret0, _ := ret[0].(store.Campaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCampaign indicates an expected call of CreateCampaign.
func (mr *MockCampaignStoreMockRecorder) CreateCampaign(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCampaign", reflect.TypeOf((*MockCampaignStore)(nil).CreateCampaign), ctx, params)
}

// DeleteCampaign mocks base method.
func (m *MockCampaignStore) DeleteCampaign(ctx context.Context, accountID, campaignID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCampaign", ctx, accountID, campaignID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCampaign indicates an expected call of DeleteCampaign.
func (mr *MockCampaignStoreMockRecorder) DeleteCampaign(ctx, accountID, campaignID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCampaign", reflect.TypeOf((*MockCampaignStore)(nil).DeleteCampaign), ctx, accountID, campaignID)
}

// GetCampaignBrandingSettings mocks base method.
func (m *MockCampaignStore) GetCampaignBrandingSettings(ctx context.Context, campaignID uuid.UUID) (store.CampaignBrandingSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCampaignBrandingSettings", ctx, campaignID)
	ret0, _ := ret[0].(store.CampaignBrandingSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCampaignBrandingSettings indicates an expected call of GetCampaignBrandingSettings.
func (mr *MockCampaignStoreMockRecorder) GetCampaignBrandingSettings(ctx, campaignID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCampaignBrandingSettings", reflect.TypeOf((*MockCampaignStore)(nil).GetCampaignBrandingSettings), ctx, campaignID)
}

// GetCampaignByID mocks base method.
func (m *MockCampaignStore) GetCampaignByID(ctx context.Context, campaignID uuid.UUID) (store.Campaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCampaignByID", ctx, campaignID)
	ret0, _ := ret[0].(store.Campaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCampaignByID indicates an expected call of GetCampaignByID.
func (mr *MockCampaignStoreMockRecorder) GetCampaignByID(ctx, campaignID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCampaignByID", reflect.TypeOf((*MockCampaignStore)(nil).GetCampaignByID), ctx, campaignID)
}

// GetCampaignBySlug mocks base method.
func (m *MockCampaignStore) GetCampaignBySlug(ctx context.Context, accountID uuid.UUID, slug string) (store.Campaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCampaignBySlug", ctx, accountID, slug)
	ret0, _ := ret[0].(store.Campaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCampaignBySlug indicates an expected call of GetCampaignBySlug.
func (mr *MockCampaignStoreMockRecorder) GetCampaignBySlug(ctx, accountID, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCampaignBySlug", reflect.TypeOf((*MockCampaignStore)(nil).GetCampaignBySlug), ctx, accountID, slug)
}

// GetCampaignEmailSettings mocks base method.
func (m *MockCampaignStore) GetCampaignEmailSettings(ctx context.Context, campaignID uuid.UUID) (store.CampaignEmailSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCampaignEmailSettings", ctx, campaignID)
	ret0, _ := ret[0].(store.CampaignEmailSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCampaignEmailSettings indicates an expected call of GetCampaignEmailSettings.
func (mr *MockCampaignStoreMockRecorder) GetCampaignEmailSettings(ctx, campaignID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCampaignEmailSettings", reflect.TypeOf((*MockCampaignStore)(nil).GetCampaignEmailSettings), ctx, campaignID)
}

// GetCampaignFormFields mocks base method.
func (m *MockCampaignStore) GetCampaignFormFields(ctx context.Context, campaignID uuid.UUID) ([]store.CampaignFormField, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCampaignFormFields", ctx, campaignID)
	ret0, _ := ret[0].([]store.CampaignFormField)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCampaignFormFields indicates an expected call of GetCampaignFormFields.
func (mr *MockCampaignStoreMockRecorder) GetCampaignFormFields(ctx, campaignID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCampaignFormFields", reflect.TypeOf((*MockCampaignStore)(nil).GetCampaignFormFields), ctx, campaignID)
}

// GetCampaignFormSettings mocks base method.
func (m *MockCampaignStore) GetCampaignFormSettings(ctx context.Context, campaignID uuid.UUID) (store.CampaignFormSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCampaignFormSettings", ctx, campaignID)
	ret0, _ := ret[0].(store.CampaignFormSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCampaignFormSettings indicates an expected call of GetCampaignFormSettings.
func (mr *MockCampaignStoreMockRecorder) GetCampaignFormSettings(ctx, campaignID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCampaignFormSettings", reflect.TypeOf((*MockCampaignStore)(nil).GetCampaignFormSettings), ctx, campaignID)
}

// GetCampaignReferralSettings mocks base method.
func (m *MockCampaignStore) GetCampaignReferralSettings(ctx context.Context, campaignID uuid.UUID) (store.CampaignReferralSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCampaignReferralSettings", ctx, campaignID)
	ret0, _ := ret[0].(store.CampaignReferralSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCampaignReferralSettings indicates an expected call of GetCampaignReferralSettings.
func (mr *MockCampaignStoreMockRecorder) GetCampaignReferralSettings(ctx, campaignID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCampaignReferralSettings", reflect.TypeOf((*MockCampaignStore)(nil).GetCampaignReferralSettings), ctx, campaignID)
}

// GetCampaignShareMessages mocks base method.
func (m *MockCampaignStore) GetCampaignShareMessages(ctx context.Context, campaignID uuid.UUID) ([]store.CampaignShareMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCampaignShareMessages", ctx, campaignID)
	ret0, _ := ret[0].([]store.CampaignShareMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCampaignShareMessages indicates an expected call of GetCampaignShareMessages.
func (mr *MockCampaignStoreMockRecorder) GetCampaignShareMessages(ctx, campaignID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCampaignShareMessages", reflect.TypeOf((*MockCampaignStore)(nil).GetCampaignShareMessages), ctx, campaignID)
}

// GetCampaignTrackingIntegrations mocks base method.
func (m *MockCampaignStore) GetCampaignTrackingIntegrations(ctx context.Context, campaignID uuid.UUID) ([]store.CampaignTrackingIntegration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCampaignTrackingIntegrations", ctx, campaignID)
	ret0, _ := ret[0].([]store.CampaignTrackingIntegration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCampaignTrackingIntegrations indicates an expected call of GetCampaignTrackingIntegrations.
func (mr *MockCampaignStoreMockRecorder) GetCampaignTrackingIntegrations(ctx, campaignID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCampaignTrackingIntegrations", reflect.TypeOf((*MockCampaignStore)(nil).GetCampaignTrackingIntegrations), ctx, campaignID)
}

// GetCampaignWithSettings mocks base method.
func (m *MockCampaignStore) GetCampaignWithSettings(ctx context.Context, campaignID uuid.UUID) (store.Campaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCampaignWithSettings", ctx, campaignID)
	ret0, _ := ret[0].(store.Campaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCampaignWithSettings indicates an expected call of GetCampaignWithSettings.
func (mr *MockCampaignStoreMockRecorder) GetCampaignWithSettings(ctx, campaignID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCampaignWithSettings", reflect.TypeOf((*MockCampaignStore)(nil).GetCampaignWithSettings), ctx, campaignID)
}

// ListCampaigns mocks base method.
func (m *MockCampaignStore) ListCampaigns(ctx context.Context, params store.ListCampaignsParams) (store.ListCampaignsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCampaigns", ctx, params)
	ret0, _ := ret[0].(store.ListCampaignsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCampaigns indicates an expected call of ListCampaigns.
func (mr *MockCampaignStoreMockRecorder) ListCampaigns(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCampaigns", reflect.TypeOf((*MockCampaignStore)(nil).ListCampaigns), ctx, params)
}

// LoadCampaignsSettings mocks base method.
func (m *MockCampaignStore) LoadCampaignsSettings(ctx context.Context, campaigns []store.Campaign) ([]store.Campaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadCampaignsSettings", ctx, campaigns)
	ret0, _ := ret[0].([]store.Campaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadCampaignsSettings indicates an expected call of LoadCampaignsSettings.
func (mr *MockCampaignStoreMockRecorder) LoadCampaignsSettings(ctx, campaigns any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadCampaignsSettings", reflect.TypeOf((*MockCampaignStore)(nil).LoadCampaignsSettings), ctx, campaigns)
}

// ReplaceCampaignFormFields mocks base method.
func (m *MockCampaignStore) ReplaceCampaignFormFields(ctx context.Context, campaignID uuid.UUID, fields []store.CreateCampaignFormFieldParams) ([]store.CampaignFormField, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceCampaignFormFields", ctx, campaignID, fields)
	ret0, _ := ret[0].([]store.CampaignFormField)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReplaceCampaignFormFields indicates an expected call of ReplaceCampaignFormFields.
func (mr *MockCampaignStoreMockRecorder) ReplaceCampaignFormFields(ctx, campaignID, fields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceCampaignFormFields", reflect.TypeOf((*MockCampaignStore)(nil).ReplaceCampaignFormFields), ctx, campaignID, fields)
}

// ReplaceCampaignShareMessages mocks base method.
func (m *MockCampaignStore) ReplaceCampaignShareMessages(ctx context.Context, campaignID uuid.UUID, messages []store.CreateCampaignShareMessageParams) ([]store.CampaignShareMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceCampaignShareMessages", ctx, campaignID, messages)
	ret0, _ := ret[0].([]store.CampaignShareMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReplaceCampaignShareMessages indicates an expected call of ReplaceCampaignShareMessages.
func (mr *MockCampaignStoreMockRecorder) ReplaceCampaignShareMessages(ctx, campaignID, messages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceCampaignShareMessages", reflect.TypeOf((*MockCampaignStore)(nil).ReplaceCampaignShareMessages), ctx, campaignID, messages)
}

// ReplaceCampaignTrackingIntegrations mocks base method.
func (m *MockCampaignStore) ReplaceCampaignTrackingIntegrations(ctx context.Context, campaignID uuid.UUID, integrations []store.CreateCampaignTrackingIntegrationParams) ([]store.CampaignTrackingIntegration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceCampaignTrackingIntegrations", ctx, campaignID, integrations)
	ret0, _ := ret[0].([]store.CampaignTrackingIntegration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReplaceCampaignTrackingIntegrations indicates an expected call of ReplaceCampaignTrackingIntegrations.
func (mr *MockCampaignStoreMockRecorder) ReplaceCampaignTrackingIntegrations(ctx, campaignID, integrations any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceCampaignTrackingIntegrations", reflect.TypeOf((*MockCampaignStore)(nil).ReplaceCampaignTrackingIntegrations), ctx, campaignID, integrations)
}

// UpdateCampaign mocks base method.
func (m *MockCampaignStore) UpdateCampaign(ctx context.Context, accountID, campaignID uuid.UUID, params store.UpdateCampaignParams) (store.Campaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCampaign", ctx, accountID, campaignID, params)
	ret0, _ := ret[0].(store.Campaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCampaign indicates an expected call of UpdateCampaign.
func (mr *MockCampaignStoreMockRecorder) UpdateCampaign(ctx, accountID, campaignID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCampaign", reflect.TypeOf((*MockCampaignStore)(nil).UpdateCampaign), ctx, accountID, campaignID, params)
}

// UpdateCampaignStatus mocks base method.
func (m *MockCampaignStore) UpdateCampaignStatus(ctx context.Context, accountID, campaignID uuid.UUID, status string) (store.Campaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCampaignStatus", ctx, accountID, campaignID, status)
	ret0, _ := ret[0].(store.Campaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCampaignStatus indicates an expected call of UpdateCampaignStatus.
func (mr *MockCampaignStoreMockRecorder) UpdateCampaignStatus(ctx, accountID, campaignID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCampaignStatus", reflect.TypeOf((*MockCampaignStore)(nil).UpdateCampaignStatus), ctx, accountID, campaignID, status)
}

// UpsertCampaignBrandingSettings mocks base method.
func (m *MockCampaignStore) UpsertCampaignBrandingSettings(ctx context.Context, params store.CreateCampaignBrandingSettingsParams) (store.CampaignBrandingSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertCampaignBrandingSettings", ctx, params)
	ret0, _ := ret[0].(store.CampaignBrandingSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertCampaignBrandingSettings indicates an expected call of UpsertCampaignBrandingSettings.
func (mr *MockCampaignStoreMockRecorder) UpsertCampaignBrandingSettings(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertCampaignBrandingSettings", reflect.TypeOf((*MockCampaignStore)(nil).UpsertCampaignBrandingSettings), ctx, params)
}

// UpsertCampaignEmailSettings mocks base method.
func (m *MockCampaignStore) UpsertCampaignEmailSettings(ctx context.Context, params store.CreateCampaignEmailSettingsParams) (store.CampaignEmailSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertCampaignEmailSettings", ctx, params)
	ret0, _ := ret[0].(store.CampaignEmailSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertCampaignEmailSettings indicates an expected call of UpsertCampaignEmailSettings.
func (mr *MockCampaignStoreMockRecorder) UpsertCampaignEmailSettings(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertCampaignEmailSettings", reflect.TypeOf((*MockCampaignStore)(nil).UpsertCampaignEmailSettings), ctx, params)
}

// UpsertCampaignFormSettings mocks base method.
func (m *MockCampaignStore) UpsertCampaignFormSettings(ctx context.Context, params store.CreateCampaignFormSettingsParams) (store.CampaignFormSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertCampaignFormSettings", ctx, params)
	ret0, _ := ret[0].(store.CampaignFormSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertCampaignFormSettings indicates an expected call of UpsertCampaignFormSettings.
func (mr *MockCampaignStoreMockRecorder) UpsertCampaignFormSettings(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertCampaignFormSettings", reflect.TypeOf((*MockCampaignStore)(nil).UpsertCampaignFormSettings), ctx, params)
}

// UpsertCampaignReferralSettings mocks base method.
func (m *MockCampaignStore) UpsertCampaignReferralSettings(ctx context.Context, params store.CreateCampaignReferralSettingsParams) (store.CampaignReferralSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertCampaignReferralSettings", ctx, params)
	ret0, _ := ret[0].(store.CampaignReferralSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertCampaignReferralSettings indicates an expected call of UpsertCampaignReferralSettings.
func (mr *MockCampaignStoreMockRecorder) UpsertCampaignReferralSettings(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertCampaignReferralSettings", reflect.TypeOf((*MockCampaignStore)(nil).UpsertCampaignReferralSettings), ctx, params)
}
