name: Build and Deploy Golang Application

on:
  push:
    branches:
      - main

jobs:
  build-and-push-ecr:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::339713122183:role/github-actions-admin-aws
          role-session-name: GitHubActions

      - name: Create ECR repository if it does not exist
        run: |
          REPO_NAME="${{ github.event.repository.name }}"
          aws ecr describe-repositories --repository-names $REPO_NAME || aws ecr create-repository --repository-name $REPO_NAME

      - name: Build, tag, and push Docker image to AWS ECR
        run: |
          REPO_NAME="${{ github.event.repository.name }}"
          IMAGE_TAG=$REPO_NAME:$GITHUB_SHA
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 123456789012.dkr.ecr.us-east-1.amazonaws.com/$REPO_NAME
          docker build -t $IMAGE_TAG .
          docker tag $IMAGE_TAG 123456789012.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_TAG
          docker push 123456789012.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_TAG
