// Code generated by MockGen. DO NOT EDIT.
// Source: processor.go
//
// Generated by this command:
//
//	mockgen -source=processor.go -destination=mocks_test.go -package=processor
//

// Package processor is a generated GoMock package.
package processor

import (
	store "base-server/internal/store"
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockEmailBlastStore is a mock of EmailBlastStore interface.
type MockEmailBlastStore struct {
	ctrl     *gomock.Controller
	recorder *MockEmailBlastStoreMockRecorder
	isgomock struct{}
}

// MockEmailBlastStoreMockRecorder is the mock recorder for MockEmailBlastStore.
type MockEmailBlastStoreMockRecorder struct {
	mock *MockEmailBlastStore
}

// NewMockEmailBlastStore creates a new mock instance.
func NewMockEmailBlastStore(ctrl *gomock.Controller) *MockEmailBlastStore {
	mock := &MockEmailBlastStore{ctrl: ctrl}
	mock.recorder = &MockEmailBlastStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailBlastStore) EXPECT() *MockEmailBlastStoreMockRecorder {
	return m.recorder
}

// CountBlastRecipientsByBlast mocks base method.
func (m *MockEmailBlastStore) CountBlastRecipientsByBlast(ctx context.Context, blastID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountBlastRecipientsByBlast", ctx, blastID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountBlastRecipientsByBlast indicates an expected call of CountBlastRecipientsByBlast.
func (mr *MockEmailBlastStoreMockRecorder) CountBlastRecipientsByBlast(ctx, blastID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountBlastRecipientsByBlast", reflect.TypeOf((*MockEmailBlastStore)(nil).CountBlastRecipientsByBlast), ctx, blastID)
}

// CountEmailBlastsByCampaign mocks base method.
func (m *MockEmailBlastStore) CountEmailBlastsByCampaign(ctx context.Context, campaignID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountEmailBlastsByCampaign", ctx, campaignID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountEmailBlastsByCampaign indicates an expected call of CountEmailBlastsByCampaign.
func (mr *MockEmailBlastStoreMockRecorder) CountEmailBlastsByCampaign(ctx, campaignID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountEmailBlastsByCampaign", reflect.TypeOf((*MockEmailBlastStore)(nil).CountEmailBlastsByCampaign), ctx, campaignID)
}

// CountUsersMatchingCriteria mocks base method.
func (m *MockEmailBlastStore) CountUsersMatchingCriteria(ctx context.Context, campaignID uuid.UUID, criteria store.SegmentFilterCriteria) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUsersMatchingCriteria", ctx, campaignID, criteria)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUsersMatchingCriteria indicates an expected call of CountUsersMatchingCriteria.
func (mr *MockEmailBlastStoreMockRecorder) CountUsersMatchingCriteria(ctx, campaignID, criteria any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUsersMatchingCriteria", reflect.TypeOf((*MockEmailBlastStore)(nil).CountUsersMatchingCriteria), ctx, campaignID, criteria)
}

// CreateBlastRecipientsBulk mocks base method.
func (m *MockEmailBlastStore) CreateBlastRecipientsBulk(ctx context.Context, blastID uuid.UUID, users []store.WaitlistUser, batchSize int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBlastRecipientsBulk", ctx, blastID, users, batchSize)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBlastRecipientsBulk indicates an expected call of CreateBlastRecipientsBulk.
func (mr *MockEmailBlastStoreMockRecorder) CreateBlastRecipientsBulk(ctx, blastID, users, batchSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBlastRecipientsBulk", reflect.TypeOf((*MockEmailBlastStore)(nil).CreateBlastRecipientsBulk), ctx, blastID, users, batchSize)
}

// CreateEmailBlast mocks base method.
func (m *MockEmailBlastStore) CreateEmailBlast(ctx context.Context, params store.CreateEmailBlastParams) (store.EmailBlast, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEmailBlast", ctx, params)
	ret0, _ := ret[0].(store.EmailBlast)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEmailBlast indicates an expected call of CreateEmailBlast.
func (mr *MockEmailBlastStoreMockRecorder) CreateEmailBlast(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEmailBlast", reflect.TypeOf((*MockEmailBlastStore)(nil).CreateEmailBlast), ctx, params)
}

// DeleteEmailBlast mocks base method.
func (m *MockEmailBlastStore) DeleteEmailBlast(ctx context.Context, blastID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEmailBlast", ctx, blastID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEmailBlast indicates an expected call of DeleteEmailBlast.
func (mr *MockEmailBlastStoreMockRecorder) DeleteEmailBlast(ctx, blastID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEmailBlast", reflect.TypeOf((*MockEmailBlastStore)(nil).DeleteEmailBlast), ctx, blastID)
}

// GetBlastRecipientStats mocks base method.
func (m *MockEmailBlastStore) GetBlastRecipientStats(ctx context.Context, blastID uuid.UUID) (store.BlastRecipientStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlastRecipientStats", ctx, blastID)
	ret0, _ := ret[0].(store.BlastRecipientStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlastRecipientStats indicates an expected call of GetBlastRecipientStats.
func (mr *MockEmailBlastStoreMockRecorder) GetBlastRecipientStats(ctx, blastID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlastRecipientStats", reflect.TypeOf((*MockEmailBlastStore)(nil).GetBlastRecipientStats), ctx, blastID)
}

// GetBlastRecipientsByBlast mocks base method.
func (m *MockEmailBlastStore) GetBlastRecipientsByBlast(ctx context.Context, blastID uuid.UUID, limit, offset int) ([]store.BlastRecipient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlastRecipientsByBlast", ctx, blastID, limit, offset)
	ret0, _ := ret[0].([]store.BlastRecipient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlastRecipientsByBlast indicates an expected call of GetBlastRecipientsByBlast.
func (mr *MockEmailBlastStoreMockRecorder) GetBlastRecipientsByBlast(ctx, blastID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlastRecipientsByBlast", reflect.TypeOf((*MockEmailBlastStore)(nil).GetBlastRecipientsByBlast), ctx, blastID, limit, offset)
}

// GetCampaignByID mocks base method.
func (m *MockEmailBlastStore) GetCampaignByID(ctx context.Context, campaignID uuid.UUID) (store.Campaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCampaignByID", ctx, campaignID)
	ret0, _ := ret[0].(store.Campaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCampaignByID indicates an expected call of GetCampaignByID.
func (mr *MockEmailBlastStoreMockRecorder) GetCampaignByID(ctx, campaignID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCampaignByID", reflect.TypeOf((*MockEmailBlastStore)(nil).GetCampaignByID), ctx, campaignID)
}

// GetEmailBlastByID mocks base method.
func (m *MockEmailBlastStore) GetEmailBlastByID(ctx context.Context, blastID uuid.UUID) (store.EmailBlast, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailBlastByID", ctx, blastID)
	ret0, _ := ret[0].(store.EmailBlast)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailBlastByID indicates an expected call of GetEmailBlastByID.
func (mr *MockEmailBlastStoreMockRecorder) GetEmailBlastByID(ctx, blastID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailBlastByID", reflect.TypeOf((*MockEmailBlastStore)(nil).GetEmailBlastByID), ctx, blastID)
}

// GetEmailBlastsByCampaign mocks base method.
func (m *MockEmailBlastStore) GetEmailBlastsByCampaign(ctx context.Context, campaignID uuid.UUID, limit, offset int) ([]store.EmailBlast, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailBlastsByCampaign", ctx, campaignID, limit, offset)
	ret0, _ := ret[0].([]store.EmailBlast)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailBlastsByCampaign indicates an expected call of GetEmailBlastsByCampaign.
func (mr *MockEmailBlastStoreMockRecorder) GetEmailBlastsByCampaign(ctx, campaignID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailBlastsByCampaign", reflect.TypeOf((*MockEmailBlastStore)(nil).GetEmailBlastsByCampaign), ctx, campaignID, limit, offset)
}

// GetEmailTemplateByID mocks base method.
func (m *MockEmailBlastStore) GetEmailTemplateByID(ctx context.Context, templateID uuid.UUID) (store.EmailTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailTemplateByID", ctx, templateID)
	ret0, _ := ret[0].(store.EmailTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailTemplateByID indicates an expected call of GetEmailTemplateByID.
func (mr *MockEmailBlastStoreMockRecorder) GetEmailTemplateByID(ctx, templateID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailTemplateByID", reflect.TypeOf((*MockEmailBlastStore)(nil).GetEmailTemplateByID), ctx, templateID)
}

// GetSegmentByID mocks base method.
func (m *MockEmailBlastStore) GetSegmentByID(ctx context.Context, segmentID uuid.UUID) (store.Segment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSegmentByID", ctx, segmentID)
	ret0, _ := ret[0].(store.Segment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSegmentByID indicates an expected call of GetSegmentByID.
func (mr *MockEmailBlastStoreMockRecorder) GetSegmentByID(ctx, segmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSegmentByID", reflect.TypeOf((*MockEmailBlastStore)(nil).GetSegmentByID), ctx, segmentID)
}

// GetUsersForBlast mocks base method.
func (m *MockEmailBlastStore) GetUsersForBlast(ctx context.Context, campaignID uuid.UUID, criteria store.SegmentFilterCriteria) ([]store.WaitlistUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersForBlast", ctx, campaignID, criteria)
	ret0, _ := ret[0].([]store.WaitlistUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersForBlast indicates an expected call of GetUsersForBlast.
func (mr *MockEmailBlastStoreMockRecorder) GetUsersForBlast(ctx, campaignID, criteria any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersForBlast", reflect.TypeOf((*MockEmailBlastStore)(nil).GetUsersForBlast), ctx, campaignID, criteria)
}

// ScheduleBlast mocks base method.
func (m *MockEmailBlastStore) ScheduleBlast(ctx context.Context, blastID uuid.UUID, scheduledAt time.Time) (store.EmailBlast, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScheduleBlast", ctx, blastID, scheduledAt)
	ret0, _ := ret[0].(store.EmailBlast)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ScheduleBlast indicates an expected call of ScheduleBlast.
func (mr *MockEmailBlastStoreMockRecorder) ScheduleBlast(ctx, blastID, scheduledAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScheduleBlast", reflect.TypeOf((*MockEmailBlastStore)(nil).ScheduleBlast), ctx, blastID, scheduledAt)
}

// UpdateEmailBlast mocks base method.
func (m *MockEmailBlastStore) UpdateEmailBlast(ctx context.Context, blastID uuid.UUID, params store.UpdateEmailBlastParams) (store.EmailBlast, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEmailBlast", ctx, blastID, params)
	ret0, _ := ret[0].(store.EmailBlast)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateEmailBlast indicates an expected call of UpdateEmailBlast.
func (mr *MockEmailBlastStoreMockRecorder) UpdateEmailBlast(ctx, blastID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEmailBlast", reflect.TypeOf((*MockEmailBlastStore)(nil).UpdateEmailBlast), ctx, blastID, params)
}

// UpdateEmailBlastStatus mocks base method.
func (m *MockEmailBlastStore) UpdateEmailBlastStatus(ctx context.Context, blastID uuid.UUID, status string, errorMessage *string) (store.EmailBlast, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEmailBlastStatus", ctx, blastID, status, errorMessage)
	ret0, _ := ret[0].(store.EmailBlast)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateEmailBlastStatus indicates an expected call of UpdateEmailBlastStatus.
func (mr *MockEmailBlastStoreMockRecorder) UpdateEmailBlastStatus(ctx, blastID, status, errorMessage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEmailBlastStatus", reflect.TypeOf((*MockEmailBlastStore)(nil).UpdateEmailBlastStatus), ctx, blastID, status, errorMessage)
}

// UpdateEmailBlastTotalRecipients mocks base method.
func (m *MockEmailBlastStore) UpdateEmailBlastTotalRecipients(ctx context.Context, blastID uuid.UUID, totalRecipients int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEmailBlastTotalRecipients", ctx, blastID, totalRecipients)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEmailBlastTotalRecipients indicates an expected call of UpdateEmailBlastTotalRecipients.
func (mr *MockEmailBlastStoreMockRecorder) UpdateEmailBlastTotalRecipients(ctx, blastID, totalRecipients any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEmailBlastTotalRecipients", reflect.TypeOf((*MockEmailBlastStore)(nil).UpdateEmailBlastTotalRecipients), ctx, blastID, totalRecipients)
}
