// Code generated by MockGen. DO NOT EDIT.
// Source: processor.go
//
// Generated by this command:
//
//	mockgen -source=processor.go -destination=mocks_test.go -package=processor
//

// Package processor is a generated GoMock package.
package processor

import (
	store "base-server/internal/store"
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockEmailBlastStore is a mock of EmailBlastStore interface.
type MockEmailBlastStore struct {
	ctrl     *gomock.Controller
	recorder *MockEmailBlastStoreMockRecorder
	isgomock struct{}
}

// MockEmailBlastStoreMockRecorder is the mock recorder for MockEmailBlastStore.
type MockEmailBlastStoreMockRecorder struct {
	mock *MockEmailBlastStore
}

// NewMockEmailBlastStore creates a new mock instance.
func NewMockEmailBlastStore(ctrl *gomock.Controller) *MockEmailBlastStore {
	mock := &MockEmailBlastStore{ctrl: ctrl}
	mock.recorder = &MockEmailBlastStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailBlastStore) EXPECT() *MockEmailBlastStoreMockRecorder {
	return m.recorder
}

// CountBlastRecipientsByBlast mocks base method.
func (m *MockEmailBlastStore) CountBlastRecipientsByBlast(ctx context.Context, blastID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountBlastRecipientsByBlast", ctx, blastID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountBlastRecipientsByBlast indicates an expected call of CountBlastRecipientsByBlast.
func (mr *MockEmailBlastStoreMockRecorder) CountBlastRecipientsByBlast(ctx, blastID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountBlastRecipientsByBlast", reflect.TypeOf((*MockEmailBlastStore)(nil).CountBlastRecipientsByBlast), ctx, blastID)
}

// CountEmailBlastsByAccount mocks base method.
func (m *MockEmailBlastStore) CountEmailBlastsByAccount(ctx context.Context, accountID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountEmailBlastsByAccount", ctx, accountID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountEmailBlastsByAccount indicates an expected call of CountEmailBlastsByAccount.
func (mr *MockEmailBlastStoreMockRecorder) CountEmailBlastsByAccount(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountEmailBlastsByAccount", reflect.TypeOf((*MockEmailBlastStore)(nil).CountEmailBlastsByAccount), ctx, accountID)
}

// CreateBlastRecipientsFromMultipleSegments mocks base method.
func (m *MockEmailBlastStore) CreateBlastRecipientsFromMultipleSegments(ctx context.Context, blastID uuid.UUID, segmentIDs []uuid.UUID, batchSize int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBlastRecipientsFromMultipleSegments", ctx, blastID, segmentIDs, batchSize)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBlastRecipientsFromMultipleSegments indicates an expected call of CreateBlastRecipientsFromMultipleSegments.
func (mr *MockEmailBlastStoreMockRecorder) CreateBlastRecipientsFromMultipleSegments(ctx, blastID, segmentIDs, batchSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBlastRecipientsFromMultipleSegments", reflect.TypeOf((*MockEmailBlastStore)(nil).CreateBlastRecipientsFromMultipleSegments), ctx, blastID, segmentIDs, batchSize)
}

// CreateEmailBlast mocks base method.
func (m *MockEmailBlastStore) CreateEmailBlast(ctx context.Context, params store.CreateEmailBlastParams) (store.EmailBlast, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEmailBlast", ctx, params)
	ret0, _ := ret[0].(store.EmailBlast)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEmailBlast indicates an expected call of CreateEmailBlast.
func (mr *MockEmailBlastStoreMockRecorder) CreateEmailBlast(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEmailBlast", reflect.TypeOf((*MockEmailBlastStore)(nil).CreateEmailBlast), ctx, params)
}

// DeleteEmailBlast mocks base method.
func (m *MockEmailBlastStore) DeleteEmailBlast(ctx context.Context, blastID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEmailBlast", ctx, blastID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEmailBlast indicates an expected call of DeleteEmailBlast.
func (mr *MockEmailBlastStoreMockRecorder) DeleteEmailBlast(ctx, blastID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEmailBlast", reflect.TypeOf((*MockEmailBlastStore)(nil).DeleteEmailBlast), ctx, blastID)
}

// GetBlastEmailTemplateByID mocks base method.
func (m *MockEmailBlastStore) GetBlastEmailTemplateByID(ctx context.Context, templateID uuid.UUID) (store.BlastEmailTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlastEmailTemplateByID", ctx, templateID)
	ret0, _ := ret[0].(store.BlastEmailTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlastEmailTemplateByID indicates an expected call of GetBlastEmailTemplateByID.
func (mr *MockEmailBlastStoreMockRecorder) GetBlastEmailTemplateByID(ctx, templateID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlastEmailTemplateByID", reflect.TypeOf((*MockEmailBlastStore)(nil).GetBlastEmailTemplateByID), ctx, templateID)
}

// GetBlastRecipientStats mocks base method.
func (m *MockEmailBlastStore) GetBlastRecipientStats(ctx context.Context, blastID uuid.UUID) (store.BlastRecipientStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlastRecipientStats", ctx, blastID)
	ret0, _ := ret[0].(store.BlastRecipientStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlastRecipientStats indicates an expected call of GetBlastRecipientStats.
func (mr *MockEmailBlastStoreMockRecorder) GetBlastRecipientStats(ctx, blastID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlastRecipientStats", reflect.TypeOf((*MockEmailBlastStore)(nil).GetBlastRecipientStats), ctx, blastID)
}

// GetBlastRecipientsByBlast mocks base method.
func (m *MockEmailBlastStore) GetBlastRecipientsByBlast(ctx context.Context, blastID uuid.UUID, limit, offset int) ([]store.BlastRecipient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlastRecipientsByBlast", ctx, blastID, limit, offset)
	ret0, _ := ret[0].([]store.BlastRecipient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlastRecipientsByBlast indicates an expected call of GetBlastRecipientsByBlast.
func (mr *MockEmailBlastStoreMockRecorder) GetBlastRecipientsByBlast(ctx, blastID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlastRecipientsByBlast", reflect.TypeOf((*MockEmailBlastStore)(nil).GetBlastRecipientsByBlast), ctx, blastID, limit, offset)
}

// GetCampaignByID mocks base method.
func (m *MockEmailBlastStore) GetCampaignByID(ctx context.Context, campaignID uuid.UUID) (store.Campaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCampaignByID", ctx, campaignID)
	ret0, _ := ret[0].(store.Campaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCampaignByID indicates an expected call of GetCampaignByID.
func (mr *MockEmailBlastStoreMockRecorder) GetCampaignByID(ctx, campaignID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCampaignByID", reflect.TypeOf((*MockEmailBlastStore)(nil).GetCampaignByID), ctx, campaignID)
}

// GetEmailBlastByID mocks base method.
func (m *MockEmailBlastStore) GetEmailBlastByID(ctx context.Context, blastID uuid.UUID) (store.EmailBlast, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailBlastByID", ctx, blastID)
	ret0, _ := ret[0].(store.EmailBlast)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailBlastByID indicates an expected call of GetEmailBlastByID.
func (mr *MockEmailBlastStoreMockRecorder) GetEmailBlastByID(ctx, blastID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailBlastByID", reflect.TypeOf((*MockEmailBlastStore)(nil).GetEmailBlastByID), ctx, blastID)
}

// GetEmailBlastsByAccount mocks base method.
func (m *MockEmailBlastStore) GetEmailBlastsByAccount(ctx context.Context, accountID uuid.UUID, limit, offset int) ([]store.EmailBlast, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailBlastsByAccount", ctx, accountID, limit, offset)
	ret0, _ := ret[0].([]store.EmailBlast)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailBlastsByAccount indicates an expected call of GetEmailBlastsByAccount.
func (mr *MockEmailBlastStoreMockRecorder) GetEmailBlastsByAccount(ctx, accountID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailBlastsByAccount", reflect.TypeOf((*MockEmailBlastStore)(nil).GetEmailBlastsByAccount), ctx, accountID, limit, offset)
}

// GetSegmentByID mocks base method.
func (m *MockEmailBlastStore) GetSegmentByID(ctx context.Context, segmentID uuid.UUID) (store.Segment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSegmentByID", ctx, segmentID)
	ret0, _ := ret[0].(store.Segment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSegmentByID indicates an expected call of GetSegmentByID.
func (mr *MockEmailBlastStoreMockRecorder) GetSegmentByID(ctx, segmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSegmentByID", reflect.TypeOf((*MockEmailBlastStore)(nil).GetSegmentByID), ctx, segmentID)
}

// PreviewBlastRecipients mocks base method.
func (m *MockEmailBlastStore) PreviewBlastRecipients(ctx context.Context, segmentIDs []uuid.UUID) (store.BlastRecipientsPreview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PreviewBlastRecipients", ctx, segmentIDs)
	ret0, _ := ret[0].(store.BlastRecipientsPreview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PreviewBlastRecipients indicates an expected call of PreviewBlastRecipients.
func (mr *MockEmailBlastStoreMockRecorder) PreviewBlastRecipients(ctx, segmentIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PreviewBlastRecipients", reflect.TypeOf((*MockEmailBlastStore)(nil).PreviewBlastRecipients), ctx, segmentIDs)
}

// ScheduleBlast mocks base method.
func (m *MockEmailBlastStore) ScheduleBlast(ctx context.Context, blastID uuid.UUID, scheduledAt time.Time) (store.EmailBlast, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScheduleBlast", ctx, blastID, scheduledAt)
	ret0, _ := ret[0].(store.EmailBlast)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ScheduleBlast indicates an expected call of ScheduleBlast.
func (mr *MockEmailBlastStoreMockRecorder) ScheduleBlast(ctx, blastID, scheduledAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScheduleBlast", reflect.TypeOf((*MockEmailBlastStore)(nil).ScheduleBlast), ctx, blastID, scheduledAt)
}

// UpdateEmailBlast mocks base method.
func (m *MockEmailBlastStore) UpdateEmailBlast(ctx context.Context, blastID uuid.UUID, params store.UpdateEmailBlastParams) (store.EmailBlast, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEmailBlast", ctx, blastID, params)
	ret0, _ := ret[0].(store.EmailBlast)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateEmailBlast indicates an expected call of UpdateEmailBlast.
func (mr *MockEmailBlastStoreMockRecorder) UpdateEmailBlast(ctx, blastID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEmailBlast", reflect.TypeOf((*MockEmailBlastStore)(nil).UpdateEmailBlast), ctx, blastID, params)
}

// UpdateEmailBlastStatus mocks base method.
func (m *MockEmailBlastStore) UpdateEmailBlastStatus(ctx context.Context, blastID uuid.UUID, status string, errorMessage *string) (store.EmailBlast, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEmailBlastStatus", ctx, blastID, status, errorMessage)
	ret0, _ := ret[0].(store.EmailBlast)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateEmailBlastStatus indicates an expected call of UpdateEmailBlastStatus.
func (mr *MockEmailBlastStoreMockRecorder) UpdateEmailBlastStatus(ctx, blastID, status, errorMessage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEmailBlastStatus", reflect.TypeOf((*MockEmailBlastStore)(nil).UpdateEmailBlastStatus), ctx, blastID, status, errorMessage)
}

// UpdateEmailBlastTotalRecipients mocks base method.
func (m *MockEmailBlastStore) UpdateEmailBlastTotalRecipients(ctx context.Context, blastID uuid.UUID, totalRecipients int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEmailBlastTotalRecipients", ctx, blastID, totalRecipients)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEmailBlastTotalRecipients indicates an expected call of UpdateEmailBlastTotalRecipients.
func (mr *MockEmailBlastStoreMockRecorder) UpdateEmailBlastTotalRecipients(ctx, blastID, totalRecipients any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEmailBlastTotalRecipients", reflect.TypeOf((*MockEmailBlastStore)(nil).UpdateEmailBlastTotalRecipients), ctx, blastID, totalRecipients)
}

// MockTierChecker is a mock of TierChecker interface.
type MockTierChecker struct {
	ctrl     *gomock.Controller
	recorder *MockTierCheckerMockRecorder
	isgomock struct{}
}

// MockTierCheckerMockRecorder is the mock recorder for MockTierChecker.
type MockTierCheckerMockRecorder struct {
	mock *MockTierChecker
}

// NewMockTierChecker creates a new mock instance.
func NewMockTierChecker(ctrl *gomock.Controller) *MockTierChecker {
	mock := &MockTierChecker{ctrl: ctrl}
	mock.recorder = &MockTierCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTierChecker) EXPECT() *MockTierCheckerMockRecorder {
	return m.recorder
}

// HasFeatureByAccountID mocks base method.
func (m *MockTierChecker) HasFeatureByAccountID(ctx context.Context, accountID uuid.UUID, featureName string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasFeatureByAccountID", ctx, accountID, featureName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasFeatureByAccountID indicates an expected call of HasFeatureByAccountID.
func (mr *MockTierCheckerMockRecorder) HasFeatureByAccountID(ctx, accountID, featureName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasFeatureByAccountID", reflect.TypeOf((*MockTierChecker)(nil).HasFeatureByAccountID), ctx, accountID, featureName)
}

// MockEventDispatcher is a mock of EventDispatcher interface.
type MockEventDispatcher struct {
	ctrl     *gomock.Controller
	recorder *MockEventDispatcherMockRecorder
	isgomock struct{}
}

// MockEventDispatcherMockRecorder is the mock recorder for MockEventDispatcher.
type MockEventDispatcherMockRecorder struct {
	mock *MockEventDispatcher
}

// NewMockEventDispatcher creates a new mock instance.
func NewMockEventDispatcher(ctrl *gomock.Controller) *MockEventDispatcher {
	mock := &MockEventDispatcher{ctrl: ctrl}
	mock.recorder = &MockEventDispatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventDispatcher) EXPECT() *MockEventDispatcherMockRecorder {
	return m.recorder
}

// DispatchBlastBatchSend mocks base method.
func (m *MockEventDispatcher) DispatchBlastBatchSend(ctx context.Context, accountID, blastID uuid.UUID, batchNumber int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DispatchBlastBatchSend", ctx, accountID, blastID, batchNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// DispatchBlastBatchSend indicates an expected call of DispatchBlastBatchSend.
func (mr *MockEventDispatcherMockRecorder) DispatchBlastBatchSend(ctx, accountID, blastID, batchNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DispatchBlastBatchSend", reflect.TypeOf((*MockEventDispatcher)(nil).DispatchBlastBatchSend), ctx, accountID, blastID, batchNumber)
}

// DispatchBlastStarted mocks base method.
func (m *MockEventDispatcher) DispatchBlastStarted(ctx context.Context, accountID, blastID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DispatchBlastStarted", ctx, accountID, blastID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DispatchBlastStarted indicates an expected call of DispatchBlastStarted.
func (mr *MockEventDispatcherMockRecorder) DispatchBlastStarted(ctx, accountID, blastID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DispatchBlastStarted", reflect.TypeOf((*MockEventDispatcher)(nil).DispatchBlastStarted), ctx, accountID, blastID)
}
