ALTER TABLE Users ADD COLUMN deleted_at TIMESTAMP DEFAULT NULL;

ALTER TABLE Email_Auth ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE Email_Auth ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE Email_Auth ADD COLUMN deleted_at TIMESTAMP DEFAULT NULL;

ALTER TABLE Oauth_Auth ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE Oauth_Auth ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE Oauth_Auth ADD COLUMN deleted_at TIMESTAMP DEFAULT NULL;

ALTER TABLE User_Auth ADD COLUMN deleted_at TIMESTAMP DEFAULT NULL;
