// Code generated by MockGen. DO NOT EDIT.
// Source: processor.go
//
// Generated by this command:
//
//	mockgen -source=processor.go -destination=mocks_test.go -package=processor
//

// Package processor is a generated GoMock package.
package processor

import (
	store "base-server/internal/store"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockReferralStore is a mock of ReferralStore interface.
type MockReferralStore struct {
	ctrl     *gomock.Controller
	recorder *MockReferralStoreMockRecorder
	isgomock struct{}
}

// MockReferralStoreMockRecorder is the mock recorder for MockReferralStore.
type MockReferralStoreMockRecorder struct {
	mock *MockReferralStore
}

// NewMockReferralStore creates a new mock instance.
func NewMockReferralStore(ctrl *gomock.Controller) *MockReferralStore {
	mock := &MockReferralStore{ctrl: ctrl}
	mock.recorder = &MockReferralStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReferralStore) EXPECT() *MockReferralStoreMockRecorder {
	return m.recorder
}

// CountReferralsByCampaignWithStatusFilter mocks base method.
func (m *MockReferralStore) CountReferralsByCampaignWithStatusFilter(ctx context.Context, campaignID uuid.UUID, status *string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountReferralsByCampaignWithStatusFilter", ctx, campaignID, status)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountReferralsByCampaignWithStatusFilter indicates an expected call of CountReferralsByCampaignWithStatusFilter.
func (mr *MockReferralStoreMockRecorder) CountReferralsByCampaignWithStatusFilter(ctx, campaignID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountReferralsByCampaignWithStatusFilter", reflect.TypeOf((*MockReferralStore)(nil).CountReferralsByCampaignWithStatusFilter), ctx, campaignID, status)
}

// CountReferralsByReferrer mocks base method.
func (m *MockReferralStore) CountReferralsByReferrer(ctx context.Context, referrerID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountReferralsByReferrer", ctx, referrerID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountReferralsByReferrer indicates an expected call of CountReferralsByReferrer.
func (mr *MockReferralStoreMockRecorder) CountReferralsByReferrer(ctx, referrerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountReferralsByReferrer", reflect.TypeOf((*MockReferralStore)(nil).CountReferralsByReferrer), ctx, referrerID)
}

// GetCampaignByID mocks base method.
func (m *MockReferralStore) GetCampaignByID(ctx context.Context, campaignID uuid.UUID) (store.Campaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCampaignByID", ctx, campaignID)
	ret0, _ := ret[0].(store.Campaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCampaignByID indicates an expected call of GetCampaignByID.
func (mr *MockReferralStoreMockRecorder) GetCampaignByID(ctx, campaignID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCampaignByID", reflect.TypeOf((*MockReferralStore)(nil).GetCampaignByID), ctx, campaignID)
}

// GetReferralsByCampaignWithStatusFilter mocks base method.
func (m *MockReferralStore) GetReferralsByCampaignWithStatusFilter(ctx context.Context, campaignID uuid.UUID, status *string, limit, offset int) ([]store.Referral, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReferralsByCampaignWithStatusFilter", ctx, campaignID, status, limit, offset)
	ret0, _ := ret[0].([]store.Referral)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReferralsByCampaignWithStatusFilter indicates an expected call of GetReferralsByCampaignWithStatusFilter.
func (mr *MockReferralStoreMockRecorder) GetReferralsByCampaignWithStatusFilter(ctx, campaignID, status, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReferralsByCampaignWithStatusFilter", reflect.TypeOf((*MockReferralStore)(nil).GetReferralsByCampaignWithStatusFilter), ctx, campaignID, status, limit, offset)
}

// GetReferralsByReferrerWithPagination mocks base method.
func (m *MockReferralStore) GetReferralsByReferrerWithPagination(ctx context.Context, referrerID uuid.UUID, limit, offset int) ([]store.Referral, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReferralsByReferrerWithPagination", ctx, referrerID, limit, offset)
	ret0, _ := ret[0].([]store.Referral)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReferralsByReferrerWithPagination indicates an expected call of GetReferralsByReferrerWithPagination.
func (mr *MockReferralStoreMockRecorder) GetReferralsByReferrerWithPagination(ctx, referrerID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReferralsByReferrerWithPagination", reflect.TypeOf((*MockReferralStore)(nil).GetReferralsByReferrerWithPagination), ctx, referrerID, limit, offset)
}

// GetVerifiedReferralCountByReferrer mocks base method.
func (m *MockReferralStore) GetVerifiedReferralCountByReferrer(ctx context.Context, referrerID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVerifiedReferralCountByReferrer", ctx, referrerID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVerifiedReferralCountByReferrer indicates an expected call of GetVerifiedReferralCountByReferrer.
func (mr *MockReferralStoreMockRecorder) GetVerifiedReferralCountByReferrer(ctx, referrerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVerifiedReferralCountByReferrer", reflect.TypeOf((*MockReferralStore)(nil).GetVerifiedReferralCountByReferrer), ctx, referrerID)
}

// GetWaitlistUserByID mocks base method.
func (m *MockReferralStore) GetWaitlistUserByID(ctx context.Context, userID uuid.UUID) (store.WaitlistUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWaitlistUserByID", ctx, userID)
	ret0, _ := ret[0].(store.WaitlistUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWaitlistUserByID indicates an expected call of GetWaitlistUserByID.
func (mr *MockReferralStoreMockRecorder) GetWaitlistUserByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWaitlistUserByID", reflect.TypeOf((*MockReferralStore)(nil).GetWaitlistUserByID), ctx, userID)
}

// GetWaitlistUserByReferralCode mocks base method.
func (m *MockReferralStore) GetWaitlistUserByReferralCode(ctx context.Context, referralCode string) (store.WaitlistUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWaitlistUserByReferralCode", ctx, referralCode)
	ret0, _ := ret[0].(store.WaitlistUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWaitlistUserByReferralCode indicates an expected call of GetWaitlistUserByReferralCode.
func (mr *MockReferralStoreMockRecorder) GetWaitlistUserByReferralCode(ctx, referralCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWaitlistUserByReferralCode", reflect.TypeOf((*MockReferralStore)(nil).GetWaitlistUserByReferralCode), ctx, referralCode)
}
