// Code generated by MockGen. DO NOT EDIT.
// Source: ../types.go
//
// Generated by this command:
//
//	mockgen -source=../types.go -destination=mocks_test.go -package=service
//

// Package service is a generated GoMock package.
package service

import (
	integrations "base-server/internal/integrations"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockDeliverer is a mock of Deliverer interface.
type MockDeliverer struct {
	ctrl     *gomock.Controller
	recorder *MockDelivererMockRecorder
	isgomock struct{}
}

// MockDelivererMockRecorder is the mock recorder for MockDeliverer.
type MockDelivererMockRecorder struct {
	mock *MockDeliverer
}

// NewMockDeliverer creates a new mock instance.
func NewMockDeliverer(ctrl *gomock.Controller) *MockDeliverer {
	mock := &MockDeliverer{ctrl: ctrl}
	mock.recorder = &MockDelivererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeliverer) EXPECT() *MockDelivererMockRecorder {
	return m.recorder
}

// Deliver mocks base method.
func (m *MockDeliverer) Deliver(ctx context.Context, subscription integrations.Subscription, event integrations.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deliver", ctx, subscription, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Deliver indicates an expected call of Deliver.
func (mr *MockDelivererMockRecorder) Deliver(ctx, subscription, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deliver", reflect.TypeOf((*MockDeliverer)(nil).Deliver), ctx, subscription, event)
}

// FormatPayload mocks base method.
func (m *MockDeliverer) FormatPayload(event integrations.Event, config map[string]any) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FormatPayload", event, config)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FormatPayload indicates an expected call of FormatPayload.
func (mr *MockDelivererMockRecorder) FormatPayload(event, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FormatPayload", reflect.TypeOf((*MockDeliverer)(nil).FormatPayload), event, config)
}

// Type mocks base method.
func (m *MockDeliverer) Type() integrations.IntegrationType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(integrations.IntegrationType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockDelivererMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockDeliverer)(nil).Type))
}

// MockIntegrationStore is a mock of IntegrationStore interface.
type MockIntegrationStore struct {
	ctrl     *gomock.Controller
	recorder *MockIntegrationStoreMockRecorder
	isgomock struct{}
}

// MockIntegrationStoreMockRecorder is the mock recorder for MockIntegrationStore.
type MockIntegrationStoreMockRecorder struct {
	mock *MockIntegrationStore
}

// NewMockIntegrationStore creates a new mock instance.
func NewMockIntegrationStore(ctrl *gomock.Controller) *MockIntegrationStore {
	mock := &MockIntegrationStore{ctrl: ctrl}
	mock.recorder = &MockIntegrationStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIntegrationStore) EXPECT() *MockIntegrationStoreMockRecorder {
	return m.recorder
}

// CreateDelivery mocks base method.
func (m *MockIntegrationStore) CreateDelivery(ctx context.Context, params integrations.CreateDeliveryParams) (integrations.Delivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDelivery", ctx, params)
	ret0, _ := ret[0].(integrations.Delivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDelivery indicates an expected call of CreateDelivery.
func (mr *MockIntegrationStoreMockRecorder) CreateDelivery(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDelivery", reflect.TypeOf((*MockIntegrationStore)(nil).CreateDelivery), ctx, params)
}

// CreateIntegrationSubscription mocks base method.
func (m *MockIntegrationStore) CreateIntegrationSubscription(ctx context.Context, params integrations.CreateSubscriptionParams) (integrations.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIntegrationSubscription", ctx, params)
	ret0, _ := ret[0].(integrations.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateIntegrationSubscription indicates an expected call of CreateIntegrationSubscription.
func (mr *MockIntegrationStoreMockRecorder) CreateIntegrationSubscription(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIntegrationSubscription", reflect.TypeOf((*MockIntegrationStore)(nil).CreateIntegrationSubscription), ctx, params)
}

// DeleteIntegrationSubscription mocks base method.
func (m *MockIntegrationStore) DeleteIntegrationSubscription(ctx context.Context, subscriptionID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIntegrationSubscription", ctx, subscriptionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIntegrationSubscription indicates an expected call of DeleteIntegrationSubscription.
func (mr *MockIntegrationStoreMockRecorder) DeleteIntegrationSubscription(ctx, subscriptionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIntegrationSubscription", reflect.TypeOf((*MockIntegrationStore)(nil).DeleteIntegrationSubscription), ctx, subscriptionID)
}

// DeleteIntegrationSubscriptionsByAPIKey mocks base method.
func (m *MockIntegrationStore) DeleteIntegrationSubscriptionsByAPIKey(ctx context.Context, apiKeyID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIntegrationSubscriptionsByAPIKey", ctx, apiKeyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIntegrationSubscriptionsByAPIKey indicates an expected call of DeleteIntegrationSubscriptionsByAPIKey.
func (mr *MockIntegrationStoreMockRecorder) DeleteIntegrationSubscriptionsByAPIKey(ctx, apiKeyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIntegrationSubscriptionsByAPIKey", reflect.TypeOf((*MockIntegrationStore)(nil).DeleteIntegrationSubscriptionsByAPIKey), ctx, apiKeyID)
}

// GetActiveIntegrationSubscriptionsForEvent mocks base method.
func (m *MockIntegrationStore) GetActiveIntegrationSubscriptionsForEvent(ctx context.Context, accountID uuid.UUID, eventType string, campaignID *uuid.UUID) ([]integrations.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveIntegrationSubscriptionsForEvent", ctx, accountID, eventType, campaignID)
	ret0, _ := ret[0].([]integrations.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveIntegrationSubscriptionsForEvent indicates an expected call of GetActiveIntegrationSubscriptionsForEvent.
func (mr *MockIntegrationStoreMockRecorder) GetActiveIntegrationSubscriptionsForEvent(ctx, accountID, eventType, campaignID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveIntegrationSubscriptionsForEvent", reflect.TypeOf((*MockIntegrationStore)(nil).GetActiveIntegrationSubscriptionsForEvent), ctx, accountID, eventType, campaignID)
}

// GetDeliveriesByAccount mocks base method.
func (m *MockIntegrationStore) GetDeliveriesByAccount(ctx context.Context, accountID uuid.UUID, limit, offset int) ([]integrations.Delivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeliveriesByAccount", ctx, accountID, limit, offset)
	ret0, _ := ret[0].([]integrations.Delivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeliveriesByAccount indicates an expected call of GetDeliveriesByAccount.
func (mr *MockIntegrationStoreMockRecorder) GetDeliveriesByAccount(ctx, accountID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeliveriesByAccount", reflect.TypeOf((*MockIntegrationStore)(nil).GetDeliveriesByAccount), ctx, accountID, limit, offset)
}

// GetDeliveriesBySubscription mocks base method.
func (m *MockIntegrationStore) GetDeliveriesBySubscription(ctx context.Context, subscriptionID uuid.UUID, limit, offset int) ([]integrations.Delivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeliveriesBySubscription", ctx, subscriptionID, limit, offset)
	ret0, _ := ret[0].([]integrations.Delivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeliveriesBySubscription indicates an expected call of GetDeliveriesBySubscription.
func (mr *MockIntegrationStoreMockRecorder) GetDeliveriesBySubscription(ctx, subscriptionID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeliveriesBySubscription", reflect.TypeOf((*MockIntegrationStore)(nil).GetDeliveriesBySubscription), ctx, subscriptionID, limit, offset)
}

// GetIntegrationSubscriptionByID mocks base method.
func (m *MockIntegrationStore) GetIntegrationSubscriptionByID(ctx context.Context, subscriptionID uuid.UUID) (integrations.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIntegrationSubscriptionByID", ctx, subscriptionID)
	ret0, _ := ret[0].(integrations.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIntegrationSubscriptionByID indicates an expected call of GetIntegrationSubscriptionByID.
func (mr *MockIntegrationStoreMockRecorder) GetIntegrationSubscriptionByID(ctx, subscriptionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIntegrationSubscriptionByID", reflect.TypeOf((*MockIntegrationStore)(nil).GetIntegrationSubscriptionByID), ctx, subscriptionID)
}

// GetIntegrationSubscriptionsByAccount mocks base method.
func (m *MockIntegrationStore) GetIntegrationSubscriptionsByAccount(ctx context.Context, accountID uuid.UUID, integrationType *integrations.IntegrationType) ([]integrations.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIntegrationSubscriptionsByAccount", ctx, accountID, integrationType)
	ret0, _ := ret[0].([]integrations.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIntegrationSubscriptionsByAccount indicates an expected call of GetIntegrationSubscriptionsByAccount.
func (mr *MockIntegrationStoreMockRecorder) GetIntegrationSubscriptionsByAccount(ctx, accountID, integrationType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIntegrationSubscriptionsByAccount", reflect.TypeOf((*MockIntegrationStore)(nil).GetIntegrationSubscriptionsByAccount), ctx, accountID, integrationType)
}

// UpdateDeliveryStatus mocks base method.
func (m *MockIntegrationStore) UpdateDeliveryStatus(ctx context.Context, deliveryID uuid.UUID, status string, responseStatus, durationMs *int, errorMsg *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDeliveryStatus", ctx, deliveryID, status, responseStatus, durationMs, errorMsg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDeliveryStatus indicates an expected call of UpdateDeliveryStatus.
func (mr *MockIntegrationStoreMockRecorder) UpdateDeliveryStatus(ctx, deliveryID, status, responseStatus, durationMs, errorMsg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDeliveryStatus", reflect.TypeOf((*MockIntegrationStore)(nil).UpdateDeliveryStatus), ctx, deliveryID, status, responseStatus, durationMs, errorMsg)
}

// UpdateIntegrationSubscriptionStats mocks base method.
func (m *MockIntegrationStore) UpdateIntegrationSubscriptionStats(ctx context.Context, subscriptionID uuid.UUID, success bool, errorMsg *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIntegrationSubscriptionStats", ctx, subscriptionID, success, errorMsg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateIntegrationSubscriptionStats indicates an expected call of UpdateIntegrationSubscriptionStats.
func (mr *MockIntegrationStoreMockRecorder) UpdateIntegrationSubscriptionStats(ctx, subscriptionID, success, errorMsg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIntegrationSubscriptionStats", reflect.TypeOf((*MockIntegrationStore)(nil).UpdateIntegrationSubscriptionStats), ctx, subscriptionID, success, errorMsg)
}
