// Code generated by MockGen. DO NOT EDIT.
// Source: processor.go
//
// Generated by this command:
//
//	mockgen -source=processor.go -destination=mocks_test.go -package=processor
//

// Package processor is a generated GoMock package.
package processor

import (
	products "base-server/internal/money/products"
	subscriptions "base-server/internal/money/subscriptions"
	store "base-server/internal/store"
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	stripe "github.com/stripe/stripe-go/v79"
	gomock "go.uber.org/mock/gomock"
)

// MockBillingProcessorInterface is a mock of BillingProcessorInterface interface.
type MockBillingProcessorInterface struct {
	ctrl     *gomock.Controller
	recorder *MockBillingProcessorInterfaceMockRecorder
	isgomock struct{}
}

// MockBillingProcessorInterfaceMockRecorder is the mock recorder for MockBillingProcessorInterface.
type MockBillingProcessorInterfaceMockRecorder struct {
	mock *MockBillingProcessorInterface
}

// NewMockBillingProcessorInterface creates a new mock instance.
func NewMockBillingProcessorInterface(ctrl *gomock.Controller) *MockBillingProcessorInterface {
	mock := &MockBillingProcessorInterface{ctrl: ctrl}
	mock.recorder = &MockBillingProcessorInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBillingProcessorInterface) EXPECT() *MockBillingProcessorInterfaceMockRecorder {
	return m.recorder
}

// CancelSubscription mocks base method.
func (m *MockBillingProcessorInterface) CancelSubscription(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelSubscription", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelSubscription indicates an expected call of CancelSubscription.
func (mr *MockBillingProcessorInterfaceMockRecorder) CancelSubscription(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelSubscription", reflect.TypeOf((*MockBillingProcessorInterface)(nil).CancelSubscription), ctx, userID)
}

// CancelSubscriptionBySubscriptionExternalID mocks base method.
func (m *MockBillingProcessorInterface) CancelSubscriptionBySubscriptionExternalID(ctx context.Context, stripSubID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelSubscriptionBySubscriptionExternalID", ctx, stripSubID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelSubscriptionBySubscriptionExternalID indicates an expected call of CancelSubscriptionBySubscriptionExternalID.
func (mr *MockBillingProcessorInterfaceMockRecorder) CancelSubscriptionBySubscriptionExternalID(ctx, stripSubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelSubscriptionBySubscriptionExternalID", reflect.TypeOf((*MockBillingProcessorInterface)(nil).CancelSubscriptionBySubscriptionExternalID), ctx, stripSubID)
}

// CreateCheckoutSession mocks base method.
func (m *MockBillingProcessorInterface) CreateCheckoutSession(ctx context.Context, userID uuid.UUID, priceID string) (*stripe.CheckoutSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCheckoutSession", ctx, userID, priceID)
	ret0, _ := ret[0].(*stripe.CheckoutSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCheckoutSession indicates an expected call of CreateCheckoutSession.
func (mr *MockBillingProcessorInterfaceMockRecorder) CreateCheckoutSession(ctx, userID, priceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCheckoutSession", reflect.TypeOf((*MockBillingProcessorInterface)(nil).CreateCheckoutSession), ctx, userID, priceID)
}

// CreateCustomerPortal mocks base method.
func (m *MockBillingProcessorInterface) CreateCustomerPortal(ctx context.Context, user uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCustomerPortal", ctx, user)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCustomerPortal indicates an expected call of CreateCustomerPortal.
func (mr *MockBillingProcessorInterfaceMockRecorder) CreateCustomerPortal(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCustomerPortal", reflect.TypeOf((*MockBillingProcessorInterface)(nil).CreateCustomerPortal), ctx, user)
}

// CreateStripeCustomer mocks base method.
func (m *MockBillingProcessorInterface) CreateStripeCustomer(ctx context.Context, email string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStripeCustomer", ctx, email)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStripeCustomer indicates an expected call of CreateStripeCustomer.
func (mr *MockBillingProcessorInterfaceMockRecorder) CreateStripeCustomer(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStripeCustomer", reflect.TypeOf((*MockBillingProcessorInterface)(nil).CreateStripeCustomer), ctx, email)
}

// CreateStripePaymentIntent mocks base method.
func (m *MockBillingProcessorInterface) CreateStripePaymentIntent(ctx context.Context, items []PaymentIntentItem) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStripePaymentIntent", ctx, items)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStripePaymentIntent indicates an expected call of CreateStripePaymentIntent.
func (mr *MockBillingProcessorInterfaceMockRecorder) CreateStripePaymentIntent(ctx, items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStripePaymentIntent", reflect.TypeOf((*MockBillingProcessorInterface)(nil).CreateStripePaymentIntent), ctx, items)
}

// CreateSubscriptionIntent mocks base method.
func (m *MockBillingProcessorInterface) CreateSubscriptionIntent(ctx context.Context, userID uuid.UUID, priceID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubscriptionIntent", ctx, userID, priceID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSubscriptionIntent indicates an expected call of CreateSubscriptionIntent.
func (mr *MockBillingProcessorInterfaceMockRecorder) CreateSubscriptionIntent(ctx, userID, priceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubscriptionIntent", reflect.TypeOf((*MockBillingProcessorInterface)(nil).CreateSubscriptionIntent), ctx, userID, priceID)
}

// GetActiveSubscription mocks base method.
func (m *MockBillingProcessorInterface) GetActiveSubscription(ctx context.Context, userID uuid.UUID) (subscriptions.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveSubscription", ctx, userID)
	ret0, _ := ret[0].(subscriptions.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveSubscription indicates an expected call of GetActiveSubscription.
func (mr *MockBillingProcessorInterfaceMockRecorder) GetActiveSubscription(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveSubscription", reflect.TypeOf((*MockBillingProcessorInterface)(nil).GetActiveSubscription), ctx, userID)
}

// GetCheckoutSession mocks base method.
func (m *MockBillingProcessorInterface) GetCheckoutSession(ctx context.Context, sessionID string) (CheckoutSessionInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCheckoutSession", ctx, sessionID)
	ret0, _ := ret[0].(CheckoutSessionInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCheckoutSession indicates an expected call of GetCheckoutSession.
func (mr *MockBillingProcessorInterfaceMockRecorder) GetCheckoutSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCheckoutSession", reflect.TypeOf((*MockBillingProcessorInterface)(nil).GetCheckoutSession), ctx, sessionID)
}

// GetPaymentMethodForUser mocks base method.
func (m *MockBillingProcessorInterface) GetPaymentMethodForUser(ctx context.Context, userID uuid.UUID) (PaymentMethod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentMethodForUser", ctx, userID)
	ret0, _ := ret[0].(PaymentMethod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPaymentMethodForUser indicates an expected call of GetPaymentMethodForUser.
func (mr *MockBillingProcessorInterfaceMockRecorder) GetPaymentMethodForUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentMethodForUser", reflect.TypeOf((*MockBillingProcessorInterface)(nil).GetPaymentMethodForUser), ctx, userID)
}

// HandleWebhook mocks base method.
func (m *MockBillingProcessorInterface) HandleWebhook(ctx context.Context, event stripe.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleWebhook", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleWebhook indicates an expected call of HandleWebhook.
func (mr *MockBillingProcessorInterfaceMockRecorder) HandleWebhook(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleWebhook", reflect.TypeOf((*MockBillingProcessorInterface)(nil).HandleWebhook), ctx, event)
}

// InvoicePaymentFailed mocks base method.
func (m *MockBillingProcessorInterface) InvoicePaymentFailed(ctx context.Context, invoice stripe.Invoice) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvoicePaymentFailed", ctx, invoice)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvoicePaymentFailed indicates an expected call of InvoicePaymentFailed.
func (mr *MockBillingProcessorInterfaceMockRecorder) InvoicePaymentFailed(ctx, invoice any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvoicePaymentFailed", reflect.TypeOf((*MockBillingProcessorInterface)(nil).InvoicePaymentFailed), ctx, invoice)
}

// InvoicePaymentPaid mocks base method.
func (m *MockBillingProcessorInterface) InvoicePaymentPaid(ctx context.Context, invoice stripe.Invoice) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvoicePaymentPaid", ctx, invoice)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvoicePaymentPaid indicates an expected call of InvoicePaymentPaid.
func (mr *MockBillingProcessorInterfaceMockRecorder) InvoicePaymentPaid(ctx, invoice any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvoicePaymentPaid", reflect.TypeOf((*MockBillingProcessorInterface)(nil).InvoicePaymentPaid), ctx, invoice)
}

// ListPrices mocks base method.
func (m *MockBillingProcessorInterface) ListPrices(ctx context.Context) ([]products.Price, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPrices", ctx)
	ret0, _ := ret[0].([]products.Price)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPrices indicates an expected call of ListPrices.
func (mr *MockBillingProcessorInterfaceMockRecorder) ListPrices(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPrices", reflect.TypeOf((*MockBillingProcessorInterface)(nil).ListPrices), ctx)
}

// PaymentIntentSucceeded mocks base method.
func (m *MockBillingProcessorInterface) PaymentIntentSucceeded(ctx context.Context, paymentIntent stripe.PaymentIntent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PaymentIntentSucceeded", ctx, paymentIntent)
}

// PaymentIntentSucceeded indicates an expected call of PaymentIntentSucceeded.
func (mr *MockBillingProcessorInterfaceMockRecorder) PaymentIntentSucceeded(ctx, paymentIntent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PaymentIntentSucceeded", reflect.TypeOf((*MockBillingProcessorInterface)(nil).PaymentIntentSucceeded), ctx, paymentIntent)
}

// PriceCreated mocks base method.
func (m *MockBillingProcessorInterface) PriceCreated(ctx context.Context, priceCreated stripe.Price) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PriceCreated", ctx, priceCreated)
	ret0, _ := ret[0].(error)
	return ret0
}

// PriceCreated indicates an expected call of PriceCreated.
func (mr *MockBillingProcessorInterfaceMockRecorder) PriceCreated(ctx, priceCreated any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PriceCreated", reflect.TypeOf((*MockBillingProcessorInterface)(nil).PriceCreated), ctx, priceCreated)
}

// PriceDeleted mocks base method.
func (m *MockBillingProcessorInterface) PriceDeleted(ctx context.Context, priceDeleted stripe.Price) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PriceDeleted", ctx, priceDeleted)
	ret0, _ := ret[0].(error)
	return ret0
}

// PriceDeleted indicates an expected call of PriceDeleted.
func (mr *MockBillingProcessorInterfaceMockRecorder) PriceDeleted(ctx, priceDeleted any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PriceDeleted", reflect.TypeOf((*MockBillingProcessorInterface)(nil).PriceDeleted), ctx, priceDeleted)
}

// PriceUpdated mocks base method.
func (m *MockBillingProcessorInterface) PriceUpdated(ctx context.Context, priceUpdated stripe.Price) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PriceUpdated", ctx, priceUpdated)
	ret0, _ := ret[0].(error)
	return ret0
}

// PriceUpdated indicates an expected call of PriceUpdated.
func (mr *MockBillingProcessorInterfaceMockRecorder) PriceUpdated(ctx, priceUpdated any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PriceUpdated", reflect.TypeOf((*MockBillingProcessorInterface)(nil).PriceUpdated), ctx, priceUpdated)
}

// ProductCreated mocks base method.
func (m *MockBillingProcessorInterface) ProductCreated(ctx context.Context, productCreated stripe.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProductCreated", ctx, productCreated)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProductCreated indicates an expected call of ProductCreated.
func (mr *MockBillingProcessorInterfaceMockRecorder) ProductCreated(ctx, productCreated any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProductCreated", reflect.TypeOf((*MockBillingProcessorInterface)(nil).ProductCreated), ctx, productCreated)
}

// SetupPaymentMethodUpdateIntent mocks base method.
func (m *MockBillingProcessorInterface) SetupPaymentMethodUpdateIntent(ctx context.Context, userID uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetupPaymentMethodUpdateIntent", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetupPaymentMethodUpdateIntent indicates an expected call of SetupPaymentMethodUpdateIntent.
func (mr *MockBillingProcessorInterfaceMockRecorder) SetupPaymentMethodUpdateIntent(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupPaymentMethodUpdateIntent", reflect.TypeOf((*MockBillingProcessorInterface)(nil).SetupPaymentMethodUpdateIntent), ctx, userID)
}

// SubscriptionCreated mocks base method.
func (m *MockBillingProcessorInterface) SubscriptionCreated(ctx context.Context, subscription stripe.Subscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscriptionCreated", ctx, subscription)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubscriptionCreated indicates an expected call of SubscriptionCreated.
func (mr *MockBillingProcessorInterfaceMockRecorder) SubscriptionCreated(ctx, subscription any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscriptionCreated", reflect.TypeOf((*MockBillingProcessorInterface)(nil).SubscriptionCreated), ctx, subscription)
}

// SubscriptionDeleted mocks base method.
func (m *MockBillingProcessorInterface) SubscriptionDeleted(ctx context.Context, subscriptionDeleted stripe.Subscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscriptionDeleted", ctx, subscriptionDeleted)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubscriptionDeleted indicates an expected call of SubscriptionDeleted.
func (mr *MockBillingProcessorInterfaceMockRecorder) SubscriptionDeleted(ctx, subscriptionDeleted any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscriptionDeleted", reflect.TypeOf((*MockBillingProcessorInterface)(nil).SubscriptionDeleted), ctx, subscriptionDeleted)
}

// SubscriptionUpdated mocks base method.
func (m *MockBillingProcessorInterface) SubscriptionUpdated(ctx context.Context, subscription stripe.Subscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscriptionUpdated", ctx, subscription)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubscriptionUpdated indicates an expected call of SubscriptionUpdated.
func (mr *MockBillingProcessorInterfaceMockRecorder) SubscriptionUpdated(ctx, subscription any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscriptionUpdated", reflect.TypeOf((*MockBillingProcessorInterface)(nil).SubscriptionUpdated), ctx, subscription)
}

// UpdateSubscription mocks base method.
func (m *MockBillingProcessorInterface) UpdateSubscription(ctx context.Context, userID uuid.UUID, priceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubscription", ctx, userID, priceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSubscription indicates an expected call of UpdateSubscription.
func (mr *MockBillingProcessorInterfaceMockRecorder) UpdateSubscription(ctx, userID, priceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubscription", reflect.TypeOf((*MockBillingProcessorInterface)(nil).UpdateSubscription), ctx, userID, priceID)
}

// MockBillingStore is a mock of BillingStore interface.
type MockBillingStore struct {
	ctrl     *gomock.Controller
	recorder *MockBillingStoreMockRecorder
	isgomock struct{}
}

// MockBillingStoreMockRecorder is the mock recorder for MockBillingStore.
type MockBillingStoreMockRecorder struct {
	mock *MockBillingStore
}

// NewMockBillingStore creates a new mock instance.
func NewMockBillingStore(ctrl *gomock.Controller) *MockBillingStore {
	mock := &MockBillingStore{ctrl: ctrl}
	mock.recorder = &MockBillingStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBillingStore) EXPECT() *MockBillingStoreMockRecorder {
	return m.recorder
}

// GetPaymentMethodByUserID mocks base method.
func (m *MockBillingStore) GetPaymentMethodByUserID(ctx context.Context, userID uuid.UUID) (*store.PaymentMethod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentMethodByUserID", ctx, userID)
	ret0, _ := ret[0].(*store.PaymentMethod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPaymentMethodByUserID indicates an expected call of GetPaymentMethodByUserID.
func (mr *MockBillingStoreMockRecorder) GetPaymentMethodByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentMethodByUserID", reflect.TypeOf((*MockBillingStore)(nil).GetPaymentMethodByUserID), ctx, userID)
}

// GetPriceByID mocks base method.
func (m *MockBillingStore) GetPriceByID(ctx context.Context, priceID string) (store.Price, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPriceByID", ctx, priceID)
	ret0, _ := ret[0].(store.Price)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPriceByID indicates an expected call of GetPriceByID.
func (mr *MockBillingStoreMockRecorder) GetPriceByID(ctx, priceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPriceByID", reflect.TypeOf((*MockBillingStore)(nil).GetPriceByID), ctx, priceID)
}

// GetStripeCustomerIDByUserExternalID mocks base method.
func (m *MockBillingStore) GetStripeCustomerIDByUserExternalID(ctx context.Context, ID uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStripeCustomerIDByUserExternalID", ctx, ID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStripeCustomerIDByUserExternalID indicates an expected call of GetStripeCustomerIDByUserExternalID.
func (mr *MockBillingStoreMockRecorder) GetStripeCustomerIDByUserExternalID(ctx, ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStripeCustomerIDByUserExternalID", reflect.TypeOf((*MockBillingStore)(nil).GetStripeCustomerIDByUserExternalID), ctx, ID)
}

// MockProductService is a mock of ProductService interface.
type MockProductService struct {
	ctrl     *gomock.Controller
	recorder *MockProductServiceMockRecorder
	isgomock struct{}
}

// MockProductServiceMockRecorder is the mock recorder for MockProductService.
type MockProductServiceMockRecorder struct {
	mock *MockProductService
}

// NewMockProductService creates a new mock instance.
func NewMockProductService(ctrl *gomock.Controller) *MockProductService {
	mock := &MockProductService{ctrl: ctrl}
	mock.recorder = &MockProductServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductService) EXPECT() *MockProductServiceMockRecorder {
	return m.recorder
}

// CreatePrice mocks base method.
func (m *MockProductService) CreatePrice(ctx context.Context, priceCreated stripe.Price) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePrice", ctx, priceCreated)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePrice indicates an expected call of CreatePrice.
func (mr *MockProductServiceMockRecorder) CreatePrice(ctx, priceCreated any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePrice", reflect.TypeOf((*MockProductService)(nil).CreatePrice), ctx, priceCreated)
}

// CreateProduct mocks base method.
func (m *MockProductService) CreateProduct(ctx context.Context, productCreated stripe.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProduct", ctx, productCreated)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateProduct indicates an expected call of CreateProduct.
func (mr *MockProductServiceMockRecorder) CreateProduct(ctx, productCreated any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProduct", reflect.TypeOf((*MockProductService)(nil).CreateProduct), ctx, productCreated)
}

// DeletePrice mocks base method.
func (m *MockProductService) DeletePrice(ctx context.Context, priceDeleted stripe.Price) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePrice", ctx, priceDeleted)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePrice indicates an expected call of DeletePrice.
func (mr *MockProductServiceMockRecorder) DeletePrice(ctx, priceDeleted any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePrice", reflect.TypeOf((*MockProductService)(nil).DeletePrice), ctx, priceDeleted)
}

// ListPrices mocks base method.
func (m *MockProductService) ListPrices(ctx context.Context) ([]products.Price, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPrices", ctx)
	ret0, _ := ret[0].([]products.Price)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPrices indicates an expected call of ListPrices.
func (mr *MockProductServiceMockRecorder) ListPrices(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPrices", reflect.TypeOf((*MockProductService)(nil).ListPrices), ctx)
}

// UpdatePrice mocks base method.
func (m *MockProductService) UpdatePrice(ctx context.Context, priceUpdated stripe.Price) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePrice", ctx, priceUpdated)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePrice indicates an expected call of UpdatePrice.
func (mr *MockProductServiceMockRecorder) UpdatePrice(ctx, priceUpdated any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePrice", reflect.TypeOf((*MockProductService)(nil).UpdatePrice), ctx, priceUpdated)
}

// MockSubscriptionService is a mock of SubscriptionService interface.
type MockSubscriptionService struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionServiceMockRecorder
	isgomock struct{}
}

// MockSubscriptionServiceMockRecorder is the mock recorder for MockSubscriptionService.
type MockSubscriptionServiceMockRecorder struct {
	mock *MockSubscriptionService
}

// NewMockSubscriptionService creates a new mock instance.
func NewMockSubscriptionService(ctrl *gomock.Controller) *MockSubscriptionService {
	mock := &MockSubscriptionService{ctrl: ctrl}
	mock.recorder = &MockSubscriptionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionService) EXPECT() *MockSubscriptionServiceMockRecorder {
	return m.recorder
}

// CancelSubscription mocks base method.
func (m *MockSubscriptionService) CancelSubscription(ctx context.Context, subscriptionID string, cancelAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelSubscription", ctx, subscriptionID, cancelAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelSubscription indicates an expected call of CancelSubscription.
func (mr *MockSubscriptionServiceMockRecorder) CancelSubscription(ctx, subscriptionID, cancelAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelSubscription", reflect.TypeOf((*MockSubscriptionService)(nil).CancelSubscription), ctx, subscriptionID, cancelAt)
}

// CreateSubscription mocks base method.
func (m *MockSubscriptionService) CreateSubscription(ctx context.Context, subscriptionCreated stripe.Subscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubscription", ctx, subscriptionCreated)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSubscription indicates an expected call of CreateSubscription.
func (mr *MockSubscriptionServiceMockRecorder) CreateSubscription(ctx, subscriptionCreated any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubscription", reflect.TypeOf((*MockSubscriptionService)(nil).CreateSubscription), ctx, subscriptionCreated)
}

// GetSubscriptionByUserID mocks base method.
func (m *MockSubscriptionService) GetSubscriptionByUserID(ctx context.Context, userID uuid.UUID) (subscriptions.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscriptionByUserID", ctx, userID)
	ret0, _ := ret[0].(subscriptions.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscriptionByUserID indicates an expected call of GetSubscriptionByUserID.
func (mr *MockSubscriptionServiceMockRecorder) GetSubscriptionByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscriptionByUserID", reflect.TypeOf((*MockSubscriptionService)(nil).GetSubscriptionByUserID), ctx, userID)
}

// UpdateSubscription mocks base method.
func (m *MockSubscriptionService) UpdateSubscription(ctx context.Context, subscriptionUpdated stripe.Subscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubscription", ctx, subscriptionUpdated)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSubscription indicates an expected call of UpdateSubscription.
func (mr *MockSubscriptionServiceMockRecorder) UpdateSubscription(ctx, subscriptionUpdated any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubscription", reflect.TypeOf((*MockSubscriptionService)(nil).UpdateSubscription), ctx, subscriptionUpdated)
}

// MockEmailService is a mock of EmailService interface.
type MockEmailService struct {
	ctrl     *gomock.Controller
	recorder *MockEmailServiceMockRecorder
	isgomock struct{}
}

// MockEmailServiceMockRecorder is the mock recorder for MockEmailService.
type MockEmailServiceMockRecorder struct {
	mock *MockEmailService
}

// NewMockEmailService creates a new mock instance.
func NewMockEmailService(ctrl *gomock.Controller) *MockEmailService {
	mock := &MockEmailService{ctrl: ctrl}
	mock.recorder = &MockEmailServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailService) EXPECT() *MockEmailServiceMockRecorder {
	return m.recorder
}

// SendEmail mocks base method.
func (m *MockEmailService) SendEmail(ctx context.Context, to, subject, htmlContent string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEmail", ctx, to, subject, htmlContent)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendEmail indicates an expected call of SendEmail.
func (mr *MockEmailServiceMockRecorder) SendEmail(ctx, to, subject, htmlContent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmail", reflect.TypeOf((*MockEmailService)(nil).SendEmail), ctx, to, subject, htmlContent)
}
