// Code generated by MockGen. DO NOT EDIT.
// Source: processor.go
//
// Generated by this command:
//
//	mockgen -source=processor.go -destination=mocks_test.go -package=processor
//

// Package processor is a generated GoMock package.
package processor

import (
	store "base-server/internal/store"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockBlastEmailTemplateStore is a mock of BlastEmailTemplateStore interface.
type MockBlastEmailTemplateStore struct {
	ctrl     *gomock.Controller
	recorder *MockBlastEmailTemplateStoreMockRecorder
	isgomock struct{}
}

// MockBlastEmailTemplateStoreMockRecorder is the mock recorder for MockBlastEmailTemplateStore.
type MockBlastEmailTemplateStoreMockRecorder struct {
	mock *MockBlastEmailTemplateStore
}

// NewMockBlastEmailTemplateStore creates a new mock instance.
func NewMockBlastEmailTemplateStore(ctrl *gomock.Controller) *MockBlastEmailTemplateStore {
	mock := &MockBlastEmailTemplateStore{ctrl: ctrl}
	mock.recorder = &MockBlastEmailTemplateStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlastEmailTemplateStore) EXPECT() *MockBlastEmailTemplateStoreMockRecorder {
	return m.recorder
}

// CountBlastEmailTemplatesByAccount mocks base method.
func (m *MockBlastEmailTemplateStore) CountBlastEmailTemplatesByAccount(ctx context.Context, accountID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountBlastEmailTemplatesByAccount", ctx, accountID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountBlastEmailTemplatesByAccount indicates an expected call of CountBlastEmailTemplatesByAccount.
func (mr *MockBlastEmailTemplateStoreMockRecorder) CountBlastEmailTemplatesByAccount(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountBlastEmailTemplatesByAccount", reflect.TypeOf((*MockBlastEmailTemplateStore)(nil).CountBlastEmailTemplatesByAccount), ctx, accountID)
}

// CreateBlastEmailTemplate mocks base method.
func (m *MockBlastEmailTemplateStore) CreateBlastEmailTemplate(ctx context.Context, params store.CreateBlastEmailTemplateParams) (store.BlastEmailTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBlastEmailTemplate", ctx, params)
	ret0, _ := ret[0].(store.BlastEmailTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBlastEmailTemplate indicates an expected call of CreateBlastEmailTemplate.
func (mr *MockBlastEmailTemplateStoreMockRecorder) CreateBlastEmailTemplate(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBlastEmailTemplate", reflect.TypeOf((*MockBlastEmailTemplateStore)(nil).CreateBlastEmailTemplate), ctx, params)
}

// DeleteBlastEmailTemplate mocks base method.
func (m *MockBlastEmailTemplateStore) DeleteBlastEmailTemplate(ctx context.Context, templateID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBlastEmailTemplate", ctx, templateID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBlastEmailTemplate indicates an expected call of DeleteBlastEmailTemplate.
func (mr *MockBlastEmailTemplateStoreMockRecorder) DeleteBlastEmailTemplate(ctx, templateID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBlastEmailTemplate", reflect.TypeOf((*MockBlastEmailTemplateStore)(nil).DeleteBlastEmailTemplate), ctx, templateID)
}

// GetBlastEmailTemplateByID mocks base method.
func (m *MockBlastEmailTemplateStore) GetBlastEmailTemplateByID(ctx context.Context, templateID uuid.UUID) (store.BlastEmailTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlastEmailTemplateByID", ctx, templateID)
	ret0, _ := ret[0].(store.BlastEmailTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlastEmailTemplateByID indicates an expected call of GetBlastEmailTemplateByID.
func (mr *MockBlastEmailTemplateStoreMockRecorder) GetBlastEmailTemplateByID(ctx, templateID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlastEmailTemplateByID", reflect.TypeOf((*MockBlastEmailTemplateStore)(nil).GetBlastEmailTemplateByID), ctx, templateID)
}

// GetBlastEmailTemplatesByAccount mocks base method.
func (m *MockBlastEmailTemplateStore) GetBlastEmailTemplatesByAccount(ctx context.Context, accountID uuid.UUID) ([]store.BlastEmailTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlastEmailTemplatesByAccount", ctx, accountID)
	ret0, _ := ret[0].([]store.BlastEmailTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlastEmailTemplatesByAccount indicates an expected call of GetBlastEmailTemplatesByAccount.
func (mr *MockBlastEmailTemplateStoreMockRecorder) GetBlastEmailTemplatesByAccount(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlastEmailTemplatesByAccount", reflect.TypeOf((*MockBlastEmailTemplateStore)(nil).GetBlastEmailTemplatesByAccount), ctx, accountID)
}

// UpdateBlastEmailTemplate mocks base method.
func (m *MockBlastEmailTemplateStore) UpdateBlastEmailTemplate(ctx context.Context, templateID uuid.UUID, params store.UpdateBlastEmailTemplateParams) (store.BlastEmailTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBlastEmailTemplate", ctx, templateID, params)
	ret0, _ := ret[0].(store.BlastEmailTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBlastEmailTemplate indicates an expected call of UpdateBlastEmailTemplate.
func (mr *MockBlastEmailTemplateStoreMockRecorder) UpdateBlastEmailTemplate(ctx, templateID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBlastEmailTemplate", reflect.TypeOf((*MockBlastEmailTemplateStore)(nil).UpdateBlastEmailTemplate), ctx, templateID, params)
}

// MockEmailService is a mock of EmailService interface.
type MockEmailService struct {
	ctrl     *gomock.Controller
	recorder *MockEmailServiceMockRecorder
	isgomock struct{}
}

// MockEmailServiceMockRecorder is the mock recorder for MockEmailService.
type MockEmailServiceMockRecorder struct {
	mock *MockEmailService
}

// NewMockEmailService creates a new mock instance.
func NewMockEmailService(ctrl *gomock.Controller) *MockEmailService {
	mock := &MockEmailService{ctrl: ctrl}
	mock.recorder = &MockEmailServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailService) EXPECT() *MockEmailServiceMockRecorder {
	return m.recorder
}

// SendEmail mocks base method.
func (m *MockEmailService) SendEmail(ctx context.Context, to, subject, htmlContent string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEmail", ctx, to, subject, htmlContent)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendEmail indicates an expected call of SendEmail.
func (mr *MockEmailServiceMockRecorder) SendEmail(ctx, to, subject, htmlContent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmail", reflect.TypeOf((*MockEmailService)(nil).SendEmail), ctx, to, subject, htmlContent)
}

// MockTierChecker is a mock of TierChecker interface.
type MockTierChecker struct {
	ctrl     *gomock.Controller
	recorder *MockTierCheckerMockRecorder
	isgomock struct{}
}

// MockTierCheckerMockRecorder is the mock recorder for MockTierChecker.
type MockTierCheckerMockRecorder struct {
	mock *MockTierChecker
}

// NewMockTierChecker creates a new mock instance.
func NewMockTierChecker(ctrl *gomock.Controller) *MockTierChecker {
	mock := &MockTierChecker{ctrl: ctrl}
	mock.recorder = &MockTierCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTierChecker) EXPECT() *MockTierCheckerMockRecorder {
	return m.recorder
}

// HasFeatureByAccountID mocks base method.
func (m *MockTierChecker) HasFeatureByAccountID(ctx context.Context, accountID uuid.UUID, featureName string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasFeatureByAccountID", ctx, accountID, featureName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasFeatureByAccountID indicates an expected call of HasFeatureByAccountID.
func (mr *MockTierCheckerMockRecorder) HasFeatureByAccountID(ctx, accountID, featureName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasFeatureByAccountID", reflect.TypeOf((*MockTierChecker)(nil).HasFeatureByAccountID), ctx, accountID, featureName)
}
