package spam

import "strings"

// disposableDomains contains known disposable/temporary email domains
var disposableDomains = map[string]bool{
	// Popular disposable email services
	"mailinator.com":       true,
	"mailinator2.com":      true,
	"guerrillamail.com":    true,
	"guerrillamail.org":    true,
	"guerrillamail.net":    true,
	"guerrillamail.biz":    true,
	"guerrillamail.de":     true,
	"sharklasers.com":      true,
	"grr.la":               true,
	"guerrillamailblock.com": true,
	"pokemail.net":         true,
	"spam4.me":             true,

	// 10 minute mail variants
	"10minutemail.com":     true,
	"10minutemail.net":     true,
	"10minutemail.org":     true,
	"10minemail.com":       true,
	"10minmail.com":        true,

	// Temp mail services
	"tempmail.com":         true,
	"tempmail.net":         true,
	"temp-mail.org":        true,
	"temp-mail.io":         true,
	"tempail.com":          true,
	"tempr.email":          true,
	"tempmailo.com":        true,

	// Throwaway email services
	"throwaway.email":      true,
	"throwawaymail.com":    true,
	"throam.com":           true,
	"trbvm.com":            true,
	"trashmail.com":        true,
	"trashmail.net":        true,
	"trashmail.org":        true,
	"trash-mail.com":       true,
	"trashemail.de":        true,

	// Fake inbox services
	"fakeinbox.com":        true,
	"fakemailgenerator.com": true,
	"fakemail.fr":          true,
	"fakemailgenerator.net": true,

	// Yopmail variants
	"yopmail.com":          true,
	"yopmail.fr":           true,
	"yopmail.net":          true,
	"cool.fr.nf":           true,
	"jetable.fr.nf":        true,
	"courriel.fr.nf":       true,
	"moncourrier.fr.nf":    true,
	"monemail.fr.nf":       true,
	"monmail.fr.nf":        true,
	"hide.biz.st":          true,
	"mytrashmail.com":      true,

	// Maildrop
	"maildrop.cc":          true,
	"mailnesia.com":        true,

	// Discard email
	"discard.email":        true,
	"discardmail.com":      true,
	"discardmail.de":       true,
	"spambog.com":          true,
	"spambog.de":           true,
	"spambog.ru":           true,

	// Getnada
	"getnada.com":          true,
	"abyssmail.com":        true,
	"boximail.com":         true,
	"clrmail.com":          true,
	"dropjar.com":          true,
	"getairmail.com":       true,
	"givmail.com":          true,
	"inboxbear.com":        true,
	"tafmail.com":          true,
	"vomoto.com":           true,
	"zetmail.com":          true,

	// Mohmal
	"mohmal.com":           true,
	"mohmal.im":            true,
	"mohmal.in":            true,
	"mohmal.tech":          true,

	// Burner mail
	"burnermail.io":        true,
	"burnermailprovider.com": true,

	// Misc disposable domains
	"mailnator.com":        true,
	"mailtothis.com":       true,
	"mailsac.com":          true,
	"mt2009.com":           true,
	"mt2014.com":           true,
	"mynetstore.de":        true,
	"mypacks.net":          true,
	"nada.email":           true,
	"nwldx.com":            true,
	"objectmail.com":       true,
	"one-time.email":       true,
	"otherinbox.com":       true,
	"ourklips.com":         true,
	"outlawspam.com":       true,
	"owlpic.com":           true,
	"pjjkp.com":            true,
	"proxymail.eu":         true,
	"punkass.com":          true,
	"putthisinyourspamdatabase.com": true,
	"quickinbox.com":       true,
	"rcpt.at":              true,
	"receiveee.com":        true,
	"regbypass.com":        true,
	"rhyta.com":            true,
	"rklips.com":           true,
	"rmqkr.net":            true,
	"rppkn.com":            true,
	"rtrtr.com":            true,
	"s0ny.net":             true,
	"safe-mail.net":        true,
	"safersignup.de":       true,
	"safetymail.info":      true,
	"safetypost.de":        true,
	"sendspamhere.com":     true,
	"shiftmail.com":        true,
	"sinnlos-mail.de":      true,
	"siteposter.net":       true,
	"smellfear.com":        true,
	"snakemail.com":        true,
	"sofimail.com":         true,
	"sofort-mail.de":       true,
	"sogetthis.com":        true,
	"soodonims.com":        true,
	"spam.la":              true,
	"spamavert.com":        true,
	"spambob.com":          true,
	"spambob.net":          true,
	"spambob.org":          true,
	"spambox.info":         true,
	"spambox.irishspringrealty.com": true,
	"spambox.us":           true,
	"spamcannon.com":       true,
	"spamcannon.net":       true,
	"spamcero.com":         true,
	"spamcon.org":          true,
	"spamcorptastic.com":   true,
	"spamcowboy.com":       true,
	"spamcowboy.net":       true,
	"spamcowboy.org":       true,
	"spamday.com":          true,
	"spamex.com":           true,
	"spamfree24.com":       true,
	"spamfree24.de":        true,
	"spamfree24.eu":        true,
	"spamfree24.info":      true,
	"spamfree24.net":       true,
	"spamfree24.org":       true,
	"spamgoes.in":          true,
	"spamgourmet.com":      true,
	"spamgourmet.net":      true,
	"spamgourmet.org":      true,
	"spamherelots.com":     true,
	"spamhereplease.com":   true,
	"spamhole.com":         true,
	"spamify.com":          true,
	"spaminator.de":        true,
	"spamkill.info":        true,
	"spaml.com":            true,
	"spaml.de":             true,
	"spamlot.net":          true,
	"spammotel.com":        true,
	"spamobox.com":         true,
	"spamoff.de":           true,
	"spamslicer.com":       true,
	"spamspot.com":         true,
	"spamthis.co.uk":       true,
	"spamthisplease.com":   true,
	"spamtrail.com":        true,
	"spamtroll.net":        true,
	"speed.1s.fr":          true,
	"spoofmail.de":         true,
	"squizzy.de":           true,
	"ssoia.com":            true,
	"startkeys.com":        true,
	"stinkefinger.net":     true,
	"stop-my-spam.com":     true,
	"stuffmail.de":         true,
	"supergreatmail.com":   true,
	"supermailer.jp":       true,
	"superrito.com":        true,
	"superstachel.de":      true,
	"suremail.info":        true,
	"svk.jp":               true,
	"sweetxxx.de":          true,
	"tagyourself.com":      true,
	"teleworm.com":         true,
	"teleworm.us":          true,
	"tempalias.com":        true,
	"tempinbox.co.uk":      true,
	"tempinbox.com":        true,
	"tempmail.co":          true,
	"tempmail.de":          true,
	"tempmail.it":          true,
	"tempomail.fr":         true,
	"temporarily.de":       true,
	"temporarioemail.com.br": true,
	"temporaryemail.net":   true,
	"temporaryemail.us":    true,
	"temporaryforwarding.com": true,
	"temporaryinbox.com":   true,
	"thankyou2010.com":     true,
	"thc.st":               true,
	"thelimestones.com":    true,
	"thisisnotmyrealemail.com": true,
	"thismail.net":         true,
	"throwam.com":          true,
	"tilien.com":           true,
	"tittbit.in":           true,
	"tmailinator.com":      true,
	"toiea.com":            true,
	"tradermail.info":      true,
	"trbvn.com":            true,
	"trickmail.net":        true,
	"tyldd.com":            true,
	"uggsrock.com":         true,
	"upliftnow.com":        true,
	"uplipht.com":          true,
	"uroid.com":            true,
	"veryrealemail.com":    true,
	"viditag.com":          true,
	"viewcastmedia.com":    true,
	"viewcastmedia.net":    true,
	"viewcastmedia.org":    true,
	"wegwerfadresse.de":    true,
	"wegwerfemail.com":     true,
	"wegwerfemail.de":      true,
	"wegwerfmail.de":       true,
	"wegwerfmail.info":     true,
	"wegwerfmail.net":      true,
	"wegwerfmail.org":      true,
	"wetrainbayarea.com":   true,
	"wetrainbayarea.org":   true,
	"wh4f.org":             true,
	"whatiaas.com":         true,
	"whatpaas.com":         true,
	"whopy.com":            true,
	"wilemail.com":         true,
	"willhackforfood.biz":  true,
	"willselfdestruct.com": true,
	"winemaven.info":       true,
	"wolfsmail.tk":         true,
	"writeme.us":           true,
	"wronghead.com":        true,
	"wuzup.net":            true,
	"wuzupmail.net":        true,
	"wwwnew.eu":            true,
	"xagloo.com":           true,
	"xemaps.com":           true,
	"xents.com":            true,
	"xmaily.com":           true,
	"xoxy.net":             true,
	"yapped.net":           true,
	"yep.it":               true,
	"yogamaven.com":        true,
	"yuurok.com":           true,
	"zehnminutenmail.de":   true,
	"zippymail.info":       true,
	"zoaxe.com":            true,
	"zoemail.com":          true,
	"zoemail.net":          true,
	"zoemail.org":          true,
	"zomg.info":            true,
	"zxcv.com":             true,
	"zxcvbnm.com":          true,
	"zzz.com":              true,
}

// IsDisposableDomain checks if a domain is a known disposable email provider
func IsDisposableDomain(domain string) bool {
	return disposableDomains[strings.ToLower(domain)]
}
