// Code generated by MockGen. DO NOT EDIT.
// Source: processor.go
//
// Generated by this command:
//
//	mockgen -source=processor.go -destination=mocks_test.go -package=processor
//

// Package processor is a generated GoMock package.
package processor

import (
	store "base-server/internal/store"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockSegmentStore is a mock of SegmentStore interface.
type MockSegmentStore struct {
	ctrl     *gomock.Controller
	recorder *MockSegmentStoreMockRecorder
	isgomock struct{}
}

// MockSegmentStoreMockRecorder is the mock recorder for MockSegmentStore.
type MockSegmentStoreMockRecorder struct {
	mock *MockSegmentStore
}

// NewMockSegmentStore creates a new mock instance.
func NewMockSegmentStore(ctrl *gomock.Controller) *MockSegmentStore {
	mock := &MockSegmentStore{ctrl: ctrl}
	mock.recorder = &MockSegmentStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSegmentStore) EXPECT() *MockSegmentStoreMockRecorder {
	return m.recorder
}

// CountUsersMatchingCriteria mocks base method.
func (m *MockSegmentStore) CountUsersMatchingCriteria(ctx context.Context, campaignID uuid.UUID, criteria store.SegmentFilterCriteria) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUsersMatchingCriteria", ctx, campaignID, criteria)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUsersMatchingCriteria indicates an expected call of CountUsersMatchingCriteria.
func (mr *MockSegmentStoreMockRecorder) CountUsersMatchingCriteria(ctx, campaignID, criteria any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUsersMatchingCriteria", reflect.TypeOf((*MockSegmentStore)(nil).CountUsersMatchingCriteria), ctx, campaignID, criteria)
}

// CreateSegment mocks base method.
func (m *MockSegmentStore) CreateSegment(ctx context.Context, params store.CreateSegmentParams) (store.Segment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSegment", ctx, params)
	ret0, _ := ret[0].(store.Segment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSegment indicates an expected call of CreateSegment.
func (mr *MockSegmentStoreMockRecorder) CreateSegment(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSegment", reflect.TypeOf((*MockSegmentStore)(nil).CreateSegment), ctx, params)
}

// DeleteSegment mocks base method.
func (m *MockSegmentStore) DeleteSegment(ctx context.Context, segmentID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSegment", ctx, segmentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSegment indicates an expected call of DeleteSegment.
func (mr *MockSegmentStoreMockRecorder) DeleteSegment(ctx, segmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSegment", reflect.TypeOf((*MockSegmentStore)(nil).DeleteSegment), ctx, segmentID)
}

// GetActiveSegmentsByCampaign mocks base method.
func (m *MockSegmentStore) GetActiveSegmentsByCampaign(ctx context.Context, campaignID uuid.UUID) ([]store.Segment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveSegmentsByCampaign", ctx, campaignID)
	ret0, _ := ret[0].([]store.Segment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveSegmentsByCampaign indicates an expected call of GetActiveSegmentsByCampaign.
func (mr *MockSegmentStoreMockRecorder) GetActiveSegmentsByCampaign(ctx, campaignID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveSegmentsByCampaign", reflect.TypeOf((*MockSegmentStore)(nil).GetActiveSegmentsByCampaign), ctx, campaignID)
}

// GetCampaignByID mocks base method.
func (m *MockSegmentStore) GetCampaignByID(ctx context.Context, campaignID uuid.UUID) (store.Campaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCampaignByID", ctx, campaignID)
	ret0, _ := ret[0].(store.Campaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCampaignByID indicates an expected call of GetCampaignByID.
func (mr *MockSegmentStoreMockRecorder) GetCampaignByID(ctx, campaignID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCampaignByID", reflect.TypeOf((*MockSegmentStore)(nil).GetCampaignByID), ctx, campaignID)
}

// GetSegmentByID mocks base method.
func (m *MockSegmentStore) GetSegmentByID(ctx context.Context, segmentID uuid.UUID) (store.Segment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSegmentByID", ctx, segmentID)
	ret0, _ := ret[0].(store.Segment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSegmentByID indicates an expected call of GetSegmentByID.
func (mr *MockSegmentStoreMockRecorder) GetSegmentByID(ctx, segmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSegmentByID", reflect.TypeOf((*MockSegmentStore)(nil).GetSegmentByID), ctx, segmentID)
}

// GetSegmentsByCampaign mocks base method.
func (m *MockSegmentStore) GetSegmentsByCampaign(ctx context.Context, campaignID uuid.UUID) ([]store.Segment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSegmentsByCampaign", ctx, campaignID)
	ret0, _ := ret[0].([]store.Segment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSegmentsByCampaign indicates an expected call of GetSegmentsByCampaign.
func (mr *MockSegmentStoreMockRecorder) GetSegmentsByCampaign(ctx, campaignID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSegmentsByCampaign", reflect.TypeOf((*MockSegmentStore)(nil).GetSegmentsByCampaign), ctx, campaignID)
}

// GetUsersMatchingCriteria mocks base method.
func (m *MockSegmentStore) GetUsersMatchingCriteria(ctx context.Context, campaignID uuid.UUID, criteria store.SegmentFilterCriteria, limit, offset int) ([]store.WaitlistUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersMatchingCriteria", ctx, campaignID, criteria, limit, offset)
	ret0, _ := ret[0].([]store.WaitlistUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersMatchingCriteria indicates an expected call of GetUsersMatchingCriteria.
func (mr *MockSegmentStoreMockRecorder) GetUsersMatchingCriteria(ctx, campaignID, criteria, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersMatchingCriteria", reflect.TypeOf((*MockSegmentStore)(nil).GetUsersMatchingCriteria), ctx, campaignID, criteria, limit, offset)
}

// UpdateSegment mocks base method.
func (m *MockSegmentStore) UpdateSegment(ctx context.Context, segmentID uuid.UUID, params store.UpdateSegmentParams) (store.Segment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSegment", ctx, segmentID, params)
	ret0, _ := ret[0].(store.Segment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSegment indicates an expected call of UpdateSegment.
func (mr *MockSegmentStoreMockRecorder) UpdateSegment(ctx, segmentID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSegment", reflect.TypeOf((*MockSegmentStore)(nil).UpdateSegment), ctx, segmentID, params)
}

// UpdateSegmentCachedCount mocks base method.
func (m *MockSegmentStore) UpdateSegmentCachedCount(ctx context.Context, segmentID uuid.UUID, count int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSegmentCachedCount", ctx, segmentID, count)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSegmentCachedCount indicates an expected call of UpdateSegmentCachedCount.
func (mr *MockSegmentStoreMockRecorder) UpdateSegmentCachedCount(ctx, segmentID, count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSegmentCachedCount", reflect.TypeOf((*MockSegmentStore)(nil).UpdateSegmentCachedCount), ctx, segmentID, count)
}
