// Code generated by MockGen. DO NOT EDIT.
// Source: processor.go
//
// Generated by this command:
//
//	mockgen -source=processor.go -destination=mocks_test.go -package=processor
//

// Package processor is a generated GoMock package.
package processor

import (
	store "base-server/internal/store"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockEmailTemplateStore is a mock of EmailTemplateStore interface.
type MockEmailTemplateStore struct {
	ctrl     *gomock.Controller
	recorder *MockEmailTemplateStoreMockRecorder
	isgomock struct{}
}

// MockEmailTemplateStoreMockRecorder is the mock recorder for MockEmailTemplateStore.
type MockEmailTemplateStoreMockRecorder struct {
	mock *MockEmailTemplateStore
}

// NewMockEmailTemplateStore creates a new mock instance.
func NewMockEmailTemplateStore(ctrl *gomock.Controller) *MockEmailTemplateStore {
	mock := &MockEmailTemplateStore{ctrl: ctrl}
	mock.recorder = &MockEmailTemplateStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailTemplateStore) EXPECT() *MockEmailTemplateStoreMockRecorder {
	return m.recorder
}

// CreateEmailTemplate mocks base method.
func (m *MockEmailTemplateStore) CreateEmailTemplate(ctx context.Context, params store.CreateEmailTemplateParams) (store.EmailTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEmailTemplate", ctx, params)
	ret0, _ := ret[0].(store.EmailTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEmailTemplate indicates an expected call of CreateEmailTemplate.
func (mr *MockEmailTemplateStoreMockRecorder) CreateEmailTemplate(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEmailTemplate", reflect.TypeOf((*MockEmailTemplateStore)(nil).CreateEmailTemplate), ctx, params)
}

// DeleteEmailTemplate mocks base method.
func (m *MockEmailTemplateStore) DeleteEmailTemplate(ctx context.Context, templateID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEmailTemplate", ctx, templateID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEmailTemplate indicates an expected call of DeleteEmailTemplate.
func (mr *MockEmailTemplateStoreMockRecorder) DeleteEmailTemplate(ctx, templateID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEmailTemplate", reflect.TypeOf((*MockEmailTemplateStore)(nil).DeleteEmailTemplate), ctx, templateID)
}

// GetCampaignByID mocks base method.
func (m *MockEmailTemplateStore) GetCampaignByID(ctx context.Context, campaignID uuid.UUID) (store.Campaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCampaignByID", ctx, campaignID)
	ret0, _ := ret[0].(store.Campaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCampaignByID indicates an expected call of GetCampaignByID.
func (mr *MockEmailTemplateStoreMockRecorder) GetCampaignByID(ctx, campaignID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCampaignByID", reflect.TypeOf((*MockEmailTemplateStore)(nil).GetCampaignByID), ctx, campaignID)
}

// GetEmailTemplateByID mocks base method.
func (m *MockEmailTemplateStore) GetEmailTemplateByID(ctx context.Context, templateID uuid.UUID) (store.EmailTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailTemplateByID", ctx, templateID)
	ret0, _ := ret[0].(store.EmailTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailTemplateByID indicates an expected call of GetEmailTemplateByID.
func (mr *MockEmailTemplateStoreMockRecorder) GetEmailTemplateByID(ctx, templateID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailTemplateByID", reflect.TypeOf((*MockEmailTemplateStore)(nil).GetEmailTemplateByID), ctx, templateID)
}

// GetEmailTemplatesByCampaign mocks base method.
func (m *MockEmailTemplateStore) GetEmailTemplatesByCampaign(ctx context.Context, campaignID uuid.UUID) ([]store.EmailTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailTemplatesByCampaign", ctx, campaignID)
	ret0, _ := ret[0].([]store.EmailTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailTemplatesByCampaign indicates an expected call of GetEmailTemplatesByCampaign.
func (mr *MockEmailTemplateStoreMockRecorder) GetEmailTemplatesByCampaign(ctx, campaignID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailTemplatesByCampaign", reflect.TypeOf((*MockEmailTemplateStore)(nil).GetEmailTemplatesByCampaign), ctx, campaignID)
}

// UpdateEmailTemplate mocks base method.
func (m *MockEmailTemplateStore) UpdateEmailTemplate(ctx context.Context, templateID uuid.UUID, params store.UpdateEmailTemplateParams) (store.EmailTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEmailTemplate", ctx, templateID, params)
	ret0, _ := ret[0].(store.EmailTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateEmailTemplate indicates an expected call of UpdateEmailTemplate.
func (mr *MockEmailTemplateStoreMockRecorder) UpdateEmailTemplate(ctx, templateID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEmailTemplate", reflect.TypeOf((*MockEmailTemplateStore)(nil).UpdateEmailTemplate), ctx, templateID, params)
}

// MockEmailService is a mock of EmailService interface.
type MockEmailService struct {
	ctrl     *gomock.Controller
	recorder *MockEmailServiceMockRecorder
	isgomock struct{}
}

// MockEmailServiceMockRecorder is the mock recorder for MockEmailService.
type MockEmailServiceMockRecorder struct {
	mock *MockEmailService
}

// NewMockEmailService creates a new mock instance.
func NewMockEmailService(ctrl *gomock.Controller) *MockEmailService {
	mock := &MockEmailService{ctrl: ctrl}
	mock.recorder = &MockEmailServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailService) EXPECT() *MockEmailServiceMockRecorder {
	return m.recorder
}

// SendEmail mocks base method.
func (m *MockEmailService) SendEmail(ctx context.Context, to, subject, htmlContent string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEmail", ctx, to, subject, htmlContent)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendEmail indicates an expected call of SendEmail.
func (mr *MockEmailServiceMockRecorder) SendEmail(ctx, to, subject, htmlContent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmail", reflect.TypeOf((*MockEmailService)(nil).SendEmail), ctx, to, subject, htmlContent)
}
