// Code generated by MockGen. DO NOT EDIT.
// Source: processor.go
//
// Generated by this command:
//
//	mockgen -source=processor.go -destination=mocks_test.go -package=processor
//

// Package processor is a generated GoMock package.
package processor

import (
	store "base-server/internal/store"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockWaitlistStore is a mock of WaitlistStore interface.
type MockWaitlistStore struct {
	ctrl     *gomock.Controller
	recorder *MockWaitlistStoreMockRecorder
	isgomock struct{}
}

// MockWaitlistStoreMockRecorder is the mock recorder for MockWaitlistStore.
type MockWaitlistStoreMockRecorder struct {
	mock *MockWaitlistStore
}

// NewMockWaitlistStore creates a new mock instance.
func NewMockWaitlistStore(ctrl *gomock.Controller) *MockWaitlistStore {
	mock := &MockWaitlistStore{ctrl: ctrl}
	mock.recorder = &MockWaitlistStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWaitlistStore) EXPECT() *MockWaitlistStoreMockRecorder {
	return m.recorder
}

// BulkUpdateWaitlistUserPositions mocks base method.
func (m *MockWaitlistStore) BulkUpdateWaitlistUserPositions(ctx context.Context, userIDs []uuid.UUID, positions []int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUpdateWaitlistUserPositions", ctx, userIDs, positions)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkUpdateWaitlistUserPositions indicates an expected call of BulkUpdateWaitlistUserPositions.
func (mr *MockWaitlistStoreMockRecorder) BulkUpdateWaitlistUserPositions(ctx, userIDs, positions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUpdateWaitlistUserPositions", reflect.TypeOf((*MockWaitlistStore)(nil).BulkUpdateWaitlistUserPositions), ctx, userIDs, positions)
}

// CountWaitlistUsersByCampaign mocks base method.
func (m *MockWaitlistStore) CountWaitlistUsersByCampaign(ctx context.Context, campaignID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountWaitlistUsersByCampaign", ctx, campaignID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountWaitlistUsersByCampaign indicates an expected call of CountWaitlistUsersByCampaign.
func (mr *MockWaitlistStoreMockRecorder) CountWaitlistUsersByCampaign(ctx, campaignID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountWaitlistUsersByCampaign", reflect.TypeOf((*MockWaitlistStore)(nil).CountWaitlistUsersByCampaign), ctx, campaignID)
}

// CountWaitlistUsersWithFilters mocks base method.
func (m *MockWaitlistStore) CountWaitlistUsersWithFilters(ctx context.Context, campaignID uuid.UUID, status *string, verified *bool) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountWaitlistUsersWithFilters", ctx, campaignID, status, verified)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountWaitlistUsersWithFilters indicates an expected call of CountWaitlistUsersWithFilters.
func (mr *MockWaitlistStoreMockRecorder) CountWaitlistUsersWithFilters(ctx, campaignID, status, verified any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountWaitlistUsersWithFilters", reflect.TypeOf((*MockWaitlistStore)(nil).CountWaitlistUsersWithFilters), ctx, campaignID, status, verified)
}

// CreateUserChannelCodes mocks base method.
func (m *MockWaitlistStore) CreateUserChannelCodes(ctx context.Context, userID uuid.UUID, codes map[string]string) ([]store.UserChannelCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserChannelCodes", ctx, userID, codes)
	ret0, _ := ret[0].([]store.UserChannelCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserChannelCodes indicates an expected call of CreateUserChannelCodes.
func (mr *MockWaitlistStoreMockRecorder) CreateUserChannelCodes(ctx, userID, codes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserChannelCodes", reflect.TypeOf((*MockWaitlistStore)(nil).CreateUserChannelCodes), ctx, userID, codes)
}

// CreateWaitlistUser mocks base method.
func (m *MockWaitlistStore) CreateWaitlistUser(ctx context.Context, params store.CreateWaitlistUserParams) (store.WaitlistUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWaitlistUser", ctx, params)
	ret0, _ := ret[0].(store.WaitlistUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWaitlistUser indicates an expected call of CreateWaitlistUser.
func (mr *MockWaitlistStoreMockRecorder) CreateWaitlistUser(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWaitlistUser", reflect.TypeOf((*MockWaitlistStore)(nil).CreateWaitlistUser), ctx, params)
}

// DeleteWaitlistUser mocks base method.
func (m *MockWaitlistStore) DeleteWaitlistUser(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWaitlistUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWaitlistUser indicates an expected call of DeleteWaitlistUser.
func (mr *MockWaitlistStoreMockRecorder) DeleteWaitlistUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWaitlistUser", reflect.TypeOf((*MockWaitlistStore)(nil).DeleteWaitlistUser), ctx, userID)
}

// GetAllWaitlistUsersForPositionCalculation mocks base method.
func (m *MockWaitlistStore) GetAllWaitlistUsersForPositionCalculation(ctx context.Context, campaignID uuid.UUID) ([]store.WaitlistUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllWaitlistUsersForPositionCalculation", ctx, campaignID)
	ret0, _ := ret[0].([]store.WaitlistUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllWaitlistUsersForPositionCalculation indicates an expected call of GetAllWaitlistUsersForPositionCalculation.
func (mr *MockWaitlistStoreMockRecorder) GetAllWaitlistUsersForPositionCalculation(ctx, campaignID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllWaitlistUsersForPositionCalculation", reflect.TypeOf((*MockWaitlistStore)(nil).GetAllWaitlistUsersForPositionCalculation), ctx, campaignID)
}

// GetCampaignByID mocks base method.
func (m *MockWaitlistStore) GetCampaignByID(ctx context.Context, campaignID uuid.UUID) (store.Campaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCampaignByID", ctx, campaignID)
	ret0, _ := ret[0].(store.Campaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCampaignByID indicates an expected call of GetCampaignByID.
func (mr *MockWaitlistStoreMockRecorder) GetCampaignByID(ctx, campaignID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCampaignByID", reflect.TypeOf((*MockWaitlistStore)(nil).GetCampaignByID), ctx, campaignID)
}

// GetUserByChannelCode mocks base method.
func (m *MockWaitlistStore) GetUserByChannelCode(ctx context.Context, code string) (*store.WaitlistUser, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByChannelCode", ctx, code)
	ret0, _ := ret[0].(*store.WaitlistUser)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetUserByChannelCode indicates an expected call of GetUserByChannelCode.
func (mr *MockWaitlistStoreMockRecorder) GetUserByChannelCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByChannelCode", reflect.TypeOf((*MockWaitlistStore)(nil).GetUserByChannelCode), ctx, code)
}

// GetWaitlistUserByEmail mocks base method.
func (m *MockWaitlistStore) GetWaitlistUserByEmail(ctx context.Context, campaignID uuid.UUID, email string) (store.WaitlistUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWaitlistUserByEmail", ctx, campaignID, email)
	ret0, _ := ret[0].(store.WaitlistUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWaitlistUserByEmail indicates an expected call of GetWaitlistUserByEmail.
func (mr *MockWaitlistStoreMockRecorder) GetWaitlistUserByEmail(ctx, campaignID, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWaitlistUserByEmail", reflect.TypeOf((*MockWaitlistStore)(nil).GetWaitlistUserByEmail), ctx, campaignID, email)
}

// GetWaitlistUserByID mocks base method.
func (m *MockWaitlistStore) GetWaitlistUserByID(ctx context.Context, userID uuid.UUID) (store.WaitlistUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWaitlistUserByID", ctx, userID)
	ret0, _ := ret[0].(store.WaitlistUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWaitlistUserByID indicates an expected call of GetWaitlistUserByID.
func (mr *MockWaitlistStoreMockRecorder) GetWaitlistUserByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWaitlistUserByID", reflect.TypeOf((*MockWaitlistStore)(nil).GetWaitlistUserByID), ctx, userID)
}

// GetWaitlistUserByReferralCode mocks base method.
func (m *MockWaitlistStore) GetWaitlistUserByReferralCode(ctx context.Context, referralCode string) (store.WaitlistUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWaitlistUserByReferralCode", ctx, referralCode)
	ret0, _ := ret[0].(store.WaitlistUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWaitlistUserByReferralCode indicates an expected call of GetWaitlistUserByReferralCode.
func (mr *MockWaitlistStoreMockRecorder) GetWaitlistUserByReferralCode(ctx, referralCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWaitlistUserByReferralCode", reflect.TypeOf((*MockWaitlistStore)(nil).GetWaitlistUserByReferralCode), ctx, referralCode)
}

// GetWaitlistUserByVerificationToken mocks base method.
func (m *MockWaitlistStore) GetWaitlistUserByVerificationToken(ctx context.Context, token string) (store.WaitlistUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWaitlistUserByVerificationToken", ctx, token)
	ret0, _ := ret[0].(store.WaitlistUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWaitlistUserByVerificationToken indicates an expected call of GetWaitlistUserByVerificationToken.
func (mr *MockWaitlistStoreMockRecorder) GetWaitlistUserByVerificationToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWaitlistUserByVerificationToken", reflect.TypeOf((*MockWaitlistStore)(nil).GetWaitlistUserByVerificationToken), ctx, token)
}

// GetWaitlistUsersByCampaignWithFilters mocks base method.
func (m *MockWaitlistStore) GetWaitlistUsersByCampaignWithFilters(ctx context.Context, params store.ListWaitlistUsersWithFiltersParams) ([]store.WaitlistUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWaitlistUsersByCampaignWithFilters", ctx, params)
	ret0, _ := ret[0].([]store.WaitlistUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWaitlistUsersByCampaignWithFilters indicates an expected call of GetWaitlistUsersByCampaignWithFilters.
func (mr *MockWaitlistStoreMockRecorder) GetWaitlistUsersByCampaignWithFilters(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWaitlistUsersByCampaignWithFilters", reflect.TypeOf((*MockWaitlistStore)(nil).GetWaitlistUsersByCampaignWithFilters), ctx, params)
}

// IncrementReferralCount mocks base method.
func (m *MockWaitlistStore) IncrementReferralCount(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementReferralCount", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementReferralCount indicates an expected call of IncrementReferralCount.
func (mr *MockWaitlistStoreMockRecorder) IncrementReferralCount(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementReferralCount", reflect.TypeOf((*MockWaitlistStore)(nil).IncrementReferralCount), ctx, userID)
}

// IncrementVerifiedReferralCount mocks base method.
func (m *MockWaitlistStore) IncrementVerifiedReferralCount(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementVerifiedReferralCount", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementVerifiedReferralCount indicates an expected call of IncrementVerifiedReferralCount.
func (mr *MockWaitlistStoreMockRecorder) IncrementVerifiedReferralCount(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementVerifiedReferralCount", reflect.TypeOf((*MockWaitlistStore)(nil).IncrementVerifiedReferralCount), ctx, userID)
}

// SearchWaitlistUsers mocks base method.
func (m *MockWaitlistStore) SearchWaitlistUsers(ctx context.Context, params store.SearchWaitlistUsersParams) ([]store.WaitlistUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchWaitlistUsers", ctx, params)
	ret0, _ := ret[0].([]store.WaitlistUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchWaitlistUsers indicates an expected call of SearchWaitlistUsers.
func (mr *MockWaitlistStoreMockRecorder) SearchWaitlistUsers(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchWaitlistUsers", reflect.TypeOf((*MockWaitlistStore)(nil).SearchWaitlistUsers), ctx, params)
}

// UpdateVerificationToken mocks base method.
func (m *MockWaitlistStore) UpdateVerificationToken(ctx context.Context, userID uuid.UUID, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVerificationToken", ctx, userID, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateVerificationToken indicates an expected call of UpdateVerificationToken.
func (mr *MockWaitlistStoreMockRecorder) UpdateVerificationToken(ctx, userID, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVerificationToken", reflect.TypeOf((*MockWaitlistStore)(nil).UpdateVerificationToken), ctx, userID, token)
}

// UpdateWaitlistUser mocks base method.
func (m *MockWaitlistStore) UpdateWaitlistUser(ctx context.Context, userID uuid.UUID, params store.UpdateWaitlistUserParams) (store.WaitlistUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWaitlistUser", ctx, userID, params)
	ret0, _ := ret[0].(store.WaitlistUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWaitlistUser indicates an expected call of UpdateWaitlistUser.
func (mr *MockWaitlistStoreMockRecorder) UpdateWaitlistUser(ctx, userID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWaitlistUser", reflect.TypeOf((*MockWaitlistStore)(nil).UpdateWaitlistUser), ctx, userID, params)
}

// VerifyWaitlistUserEmail mocks base method.
func (m *MockWaitlistStore) VerifyWaitlistUserEmail(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyWaitlistUserEmail", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyWaitlistUserEmail indicates an expected call of VerifyWaitlistUserEmail.
func (mr *MockWaitlistStoreMockRecorder) VerifyWaitlistUserEmail(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyWaitlistUserEmail", reflect.TypeOf((*MockWaitlistStore)(nil).VerifyWaitlistUserEmail), ctx, userID)
}

// MockEventDispatcher is a mock of EventDispatcher interface.
type MockEventDispatcher struct {
	ctrl     *gomock.Controller
	recorder *MockEventDispatcherMockRecorder
	isgomock struct{}
}

// MockEventDispatcherMockRecorder is the mock recorder for MockEventDispatcher.
type MockEventDispatcherMockRecorder struct {
	mock *MockEventDispatcher
}

// NewMockEventDispatcher creates a new mock instance.
func NewMockEventDispatcher(ctrl *gomock.Controller) *MockEventDispatcher {
	mock := &MockEventDispatcher{ctrl: ctrl}
	mock.recorder = &MockEventDispatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventDispatcher) EXPECT() *MockEventDispatcherMockRecorder {
	return m.recorder
}

// DispatchUserCreated mocks base method.
func (m *MockEventDispatcher) DispatchUserCreated(ctx context.Context, accountID, campaignID uuid.UUID, userData map[string]any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DispatchUserCreated", ctx, accountID, campaignID, userData)
}

// DispatchUserCreated indicates an expected call of DispatchUserCreated.
func (mr *MockEventDispatcherMockRecorder) DispatchUserCreated(ctx, accountID, campaignID, userData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DispatchUserCreated", reflect.TypeOf((*MockEventDispatcher)(nil).DispatchUserCreated), ctx, accountID, campaignID, userData)
}

// DispatchUserVerified mocks base method.
func (m *MockEventDispatcher) DispatchUserVerified(ctx context.Context, accountID, campaignID uuid.UUID, userData map[string]any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DispatchUserVerified", ctx, accountID, campaignID, userData)
}

// DispatchUserVerified indicates an expected call of DispatchUserVerified.
func (mr *MockEventDispatcherMockRecorder) DispatchUserVerified(ctx, accountID, campaignID, userData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DispatchUserVerified", reflect.TypeOf((*MockEventDispatcher)(nil).DispatchUserVerified), ctx, accountID, campaignID, userData)
}

// MockCaptchaVerifier is a mock of CaptchaVerifier interface.
type MockCaptchaVerifier struct {
	ctrl     *gomock.Controller
	recorder *MockCaptchaVerifierMockRecorder
	isgomock struct{}
}

// MockCaptchaVerifierMockRecorder is the mock recorder for MockCaptchaVerifier.
type MockCaptchaVerifierMockRecorder struct {
	mock *MockCaptchaVerifier
}

// NewMockCaptchaVerifier creates a new mock instance.
func NewMockCaptchaVerifier(ctrl *gomock.Controller) *MockCaptchaVerifier {
	mock := &MockCaptchaVerifier{ctrl: ctrl}
	mock.recorder = &MockCaptchaVerifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCaptchaVerifier) EXPECT() *MockCaptchaVerifierMockRecorder {
	return m.recorder
}

// IsEnabled mocks base method.
func (m *MockCaptchaVerifier) IsEnabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEnabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsEnabled indicates an expected call of IsEnabled.
func (mr *MockCaptchaVerifierMockRecorder) IsEnabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEnabled", reflect.TypeOf((*MockCaptchaVerifier)(nil).IsEnabled))
}

// Verify mocks base method.
func (m *MockCaptchaVerifier) Verify(ctx context.Context, token, remoteIP string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", ctx, token, remoteIP)
	ret0, _ := ret[0].(error)
	return ret0
}

// Verify indicates an expected call of Verify.
func (mr *MockCaptchaVerifierMockRecorder) Verify(ctx, token, remoteIP any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockCaptchaVerifier)(nil).Verify), ctx, token, remoteIP)
}
