// Code generated by MockGen. DO NOT EDIT.
// Source: processor.go
//
// Generated by this command:
//
//	mockgen -source=processor.go -destination=mocks_test.go -package=processor
//

// Package processor is a generated GoMock package.
package processor

import (
	store "base-server/internal/store"
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockSpamStore is a mock of SpamStore interface.
type MockSpamStore struct {
	ctrl     *gomock.Controller
	recorder *MockSpamStoreMockRecorder
	isgomock struct{}
}

// MockSpamStoreMockRecorder is the mock recorder for MockSpamStore.
type MockSpamStoreMockRecorder struct {
	mock *MockSpamStore
}

// NewMockSpamStore creates a new mock instance.
func NewMockSpamStore(ctrl *gomock.Controller) *MockSpamStore {
	mock := &MockSpamStore{ctrl: ctrl}
	mock.recorder = &MockSpamStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpamStore) EXPECT() *MockSpamStoreMockRecorder {
	return m.recorder
}

// BlockWaitlistUser mocks base method.
func (m *MockSpamStore) BlockWaitlistUser(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockWaitlistUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// BlockWaitlistUser indicates an expected call of BlockWaitlistUser.
func (mr *MockSpamStoreMockRecorder) BlockWaitlistUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockWaitlistUser", reflect.TypeOf((*MockSpamStore)(nil).BlockWaitlistUser), ctx, userID)
}

// CountRecentSignupsByIP mocks base method.
func (m *MockSpamStore) CountRecentSignupsByIP(ctx context.Context, campaignID uuid.UUID, ip string, since time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountRecentSignupsByIP", ctx, campaignID, ip, since)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountRecentSignupsByIP indicates an expected call of CountRecentSignupsByIP.
func (mr *MockSpamStoreMockRecorder) CountRecentSignupsByIP(ctx, campaignID, ip, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountRecentSignupsByIP", reflect.TypeOf((*MockSpamStore)(nil).CountRecentSignupsByIP), ctx, campaignID, ip, since)
}

// CreateFraudDetection mocks base method.
func (m *MockSpamStore) CreateFraudDetection(ctx context.Context, params store.CreateFraudDetectionParams) (store.FraudDetection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFraudDetection", ctx, params)
	ret0, _ := ret[0].(store.FraudDetection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFraudDetection indicates an expected call of CreateFraudDetection.
func (mr *MockSpamStoreMockRecorder) CreateFraudDetection(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFraudDetection", reflect.TypeOf((*MockSpamStore)(nil).CreateFraudDetection), ctx, params)
}

// GetWaitlistUserByID mocks base method.
func (m *MockSpamStore) GetWaitlistUserByID(ctx context.Context, userID uuid.UUID) (store.WaitlistUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWaitlistUserByID", ctx, userID)
	ret0, _ := ret[0].(store.WaitlistUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWaitlistUserByID indicates an expected call of GetWaitlistUserByID.
func (mr *MockSpamStoreMockRecorder) GetWaitlistUserByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWaitlistUserByID", reflect.TypeOf((*MockSpamStore)(nil).GetWaitlistUserByID), ctx, userID)
}
