// Code generated by MockGen. DO NOT EDIT.
// Source: processor.go
//
// Generated by this command:
//
//	mockgen -source=processor.go -destination=mocks_test.go -package=processor
//

// Package processor is a generated GoMock package.
package processor

import (
	store "base-server/internal/store"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRewardStore is a mock of RewardStore interface.
type MockRewardStore struct {
	ctrl     *gomock.Controller
	recorder *MockRewardStoreMockRecorder
	isgomock struct{}
}

// MockRewardStoreMockRecorder is the mock recorder for MockRewardStore.
type MockRewardStoreMockRecorder struct {
	mock *MockRewardStore
}

// NewMockRewardStore creates a new mock instance.
func NewMockRewardStore(ctrl *gomock.Controller) *MockRewardStore {
	mock := &MockRewardStore{ctrl: ctrl}
	mock.recorder = &MockRewardStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRewardStore) EXPECT() *MockRewardStoreMockRecorder {
	return m.recorder
}

// CreateReward mocks base method.
func (m *MockRewardStore) CreateReward(ctx context.Context, params store.CreateRewardParams) (store.Reward, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReward", ctx, params)
	ret0, _ := ret[0].(store.Reward)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateReward indicates an expected call of CreateReward.
func (mr *MockRewardStoreMockRecorder) CreateReward(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReward", reflect.TypeOf((*MockRewardStore)(nil).CreateReward), ctx, params)
}

// CreateUserReward mocks base method.
func (m *MockRewardStore) CreateUserReward(ctx context.Context, params store.CreateUserRewardParams) (store.UserReward, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserReward", ctx, params)
	ret0, _ := ret[0].(store.UserReward)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserReward indicates an expected call of CreateUserReward.
func (mr *MockRewardStoreMockRecorder) CreateUserReward(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserReward", reflect.TypeOf((*MockRewardStore)(nil).CreateUserReward), ctx, params)
}

// DeleteReward mocks base method.
func (m *MockRewardStore) DeleteReward(ctx context.Context, rewardID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteReward", ctx, rewardID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteReward indicates an expected call of DeleteReward.
func (mr *MockRewardStoreMockRecorder) DeleteReward(ctx, rewardID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteReward", reflect.TypeOf((*MockRewardStore)(nil).DeleteReward), ctx, rewardID)
}

// GetRewardByID mocks base method.
func (m *MockRewardStore) GetRewardByID(ctx context.Context, rewardID uuid.UUID) (store.Reward, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRewardByID", ctx, rewardID)
	ret0, _ := ret[0].(store.Reward)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRewardByID indicates an expected call of GetRewardByID.
func (mr *MockRewardStoreMockRecorder) GetRewardByID(ctx, rewardID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRewardByID", reflect.TypeOf((*MockRewardStore)(nil).GetRewardByID), ctx, rewardID)
}

// GetRewardsByCampaign mocks base method.
func (m *MockRewardStore) GetRewardsByCampaign(ctx context.Context, campaignID uuid.UUID) ([]store.Reward, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRewardsByCampaign", ctx, campaignID)
	ret0, _ := ret[0].([]store.Reward)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRewardsByCampaign indicates an expected call of GetRewardsByCampaign.
func (mr *MockRewardStoreMockRecorder) GetRewardsByCampaign(ctx, campaignID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRewardsByCampaign", reflect.TypeOf((*MockRewardStore)(nil).GetRewardsByCampaign), ctx, campaignID)
}

// GetUserRewardsByUser mocks base method.
func (m *MockRewardStore) GetUserRewardsByUser(ctx context.Context, userID uuid.UUID) ([]store.UserReward, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRewardsByUser", ctx, userID)
	ret0, _ := ret[0].([]store.UserReward)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRewardsByUser indicates an expected call of GetUserRewardsByUser.
func (mr *MockRewardStoreMockRecorder) GetUserRewardsByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRewardsByUser", reflect.TypeOf((*MockRewardStore)(nil).GetUserRewardsByUser), ctx, userID)
}

// IncrementRewardClaimed mocks base method.
func (m *MockRewardStore) IncrementRewardClaimed(ctx context.Context, rewardID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementRewardClaimed", ctx, rewardID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementRewardClaimed indicates an expected call of IncrementRewardClaimed.
func (mr *MockRewardStoreMockRecorder) IncrementRewardClaimed(ctx, rewardID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementRewardClaimed", reflect.TypeOf((*MockRewardStore)(nil).IncrementRewardClaimed), ctx, rewardID)
}

// UpdateReward mocks base method.
func (m *MockRewardStore) UpdateReward(ctx context.Context, rewardID uuid.UUID, params store.UpdateRewardParams) (store.Reward, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateReward", ctx, rewardID, params)
	ret0, _ := ret[0].(store.Reward)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateReward indicates an expected call of UpdateReward.
func (mr *MockRewardStoreMockRecorder) UpdateReward(ctx, rewardID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateReward", reflect.TypeOf((*MockRewardStore)(nil).UpdateReward), ctx, rewardID, params)
}
