// Code generated by MockGen. DO NOT EDIT.
// Source: processor.go
//
// Generated by this command:
//
//	mockgen -source=processor.go -destination=mocks_test.go -package=processor
//

// Package processor is a generated GoMock package.
package processor

import (
	store "base-server/internal/store"
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAnalyticsStore is a mock of AnalyticsStore interface.
type MockAnalyticsStore struct {
	ctrl     *gomock.Controller
	recorder *MockAnalyticsStoreMockRecorder
	isgomock struct{}
}

// MockAnalyticsStoreMockRecorder is the mock recorder for MockAnalyticsStore.
type MockAnalyticsStoreMockRecorder struct {
	mock *MockAnalyticsStore
}

// NewMockAnalyticsStore creates a new mock instance.
func NewMockAnalyticsStore(ctrl *gomock.Controller) *MockAnalyticsStore {
	mock := &MockAnalyticsStore{ctrl: ctrl}
	mock.recorder = &MockAnalyticsStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnalyticsStore) EXPECT() *MockAnalyticsStoreMockRecorder {
	return m.recorder
}

// GetAnalyticsOverview mocks base method.
func (m *MockAnalyticsStore) GetAnalyticsOverview(ctx context.Context, campaignID uuid.UUID) (store.AnalyticsOverviewResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAnalyticsOverview", ctx, campaignID)
	ret0, _ := ret[0].(store.AnalyticsOverviewResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAnalyticsOverview indicates an expected call of GetAnalyticsOverview.
func (mr *MockAnalyticsStoreMockRecorder) GetAnalyticsOverview(ctx, campaignID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAnalyticsOverview", reflect.TypeOf((*MockAnalyticsStore)(nil).GetAnalyticsOverview), ctx, campaignID)
}

// GetCampaignByID mocks base method.
func (m *MockAnalyticsStore) GetCampaignByID(ctx context.Context, campaignID uuid.UUID) (store.Campaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCampaignByID", ctx, campaignID)
	ret0, _ := ret[0].(store.Campaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCampaignByID indicates an expected call of GetCampaignByID.
func (mr *MockAnalyticsStoreMockRecorder) GetCampaignByID(ctx, campaignID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCampaignByID", reflect.TypeOf((*MockAnalyticsStore)(nil).GetCampaignByID), ctx, campaignID)
}

// GetConversionAnalytics mocks base method.
func (m *MockAnalyticsStore) GetConversionAnalytics(ctx context.Context, campaignID uuid.UUID, dateFrom, dateTo *time.Time) (store.ConversionAnalyticsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConversionAnalytics", ctx, campaignID, dateFrom, dateTo)
	ret0, _ := ret[0].(store.ConversionAnalyticsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConversionAnalytics indicates an expected call of GetConversionAnalytics.
func (mr *MockAnalyticsStoreMockRecorder) GetConversionAnalytics(ctx, campaignID, dateFrom, dateTo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConversionAnalytics", reflect.TypeOf((*MockAnalyticsStore)(nil).GetConversionAnalytics), ctx, campaignID, dateFrom, dateTo)
}

// GetFunnelAnalytics mocks base method.
func (m *MockAnalyticsStore) GetFunnelAnalytics(ctx context.Context, campaignID uuid.UUID, dateFrom, dateTo *time.Time) ([]store.FunnelStepResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFunnelAnalytics", ctx, campaignID, dateFrom, dateTo)
	ret0, _ := ret[0].([]store.FunnelStepResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFunnelAnalytics indicates an expected call of GetFunnelAnalytics.
func (mr *MockAnalyticsStoreMockRecorder) GetFunnelAnalytics(ctx, campaignID, dateFrom, dateTo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFunnelAnalytics", reflect.TypeOf((*MockAnalyticsStore)(nil).GetFunnelAnalytics), ctx, campaignID, dateFrom, dateTo)
}

// GetReferralAnalytics mocks base method.
func (m *MockAnalyticsStore) GetReferralAnalytics(ctx context.Context, campaignID uuid.UUID, dateFrom, dateTo *time.Time) (store.ReferralAnalyticsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReferralAnalytics", ctx, campaignID, dateFrom, dateTo)
	ret0, _ := ret[0].(store.ReferralAnalyticsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReferralAnalytics indicates an expected call of GetReferralAnalytics.
func (mr *MockAnalyticsStoreMockRecorder) GetReferralAnalytics(ctx, campaignID, dateFrom, dateTo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReferralAnalytics", reflect.TypeOf((*MockAnalyticsStore)(nil).GetReferralAnalytics), ctx, campaignID, dateFrom, dateTo)
}

// GetReferralSourceBreakdown mocks base method.
func (m *MockAnalyticsStore) GetReferralSourceBreakdown(ctx context.Context, campaignID uuid.UUID, dateFrom, dateTo *time.Time) ([]store.SourceBreakdownResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReferralSourceBreakdown", ctx, campaignID, dateFrom, dateTo)
	ret0, _ := ret[0].([]store.SourceBreakdownResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReferralSourceBreakdown indicates an expected call of GetReferralSourceBreakdown.
func (mr *MockAnalyticsStoreMockRecorder) GetReferralSourceBreakdown(ctx, campaignID, dateFrom, dateTo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReferralSourceBreakdown", reflect.TypeOf((*MockAnalyticsStore)(nil).GetReferralSourceBreakdown), ctx, campaignID, dateFrom, dateTo)
}

// GetSignupSourceBreakdown mocks base method.
func (m *MockAnalyticsStore) GetSignupSourceBreakdown(ctx context.Context, campaignID uuid.UUID, dateFrom, dateTo *time.Time) ([]store.SourceBreakdownResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSignupSourceBreakdown", ctx, campaignID, dateFrom, dateTo)
	ret0, _ := ret[0].([]store.SourceBreakdownResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSignupSourceBreakdown indicates an expected call of GetSignupSourceBreakdown.
func (mr *MockAnalyticsStoreMockRecorder) GetSignupSourceBreakdown(ctx, campaignID, dateFrom, dateTo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSignupSourceBreakdown", reflect.TypeOf((*MockAnalyticsStore)(nil).GetSignupSourceBreakdown), ctx, campaignID, dateFrom, dateTo)
}

// GetSignupsBySource mocks base method.
func (m *MockAnalyticsStore) GetSignupsBySource(ctx context.Context, campaignID uuid.UUID, dateFrom, dateTo time.Time, period string) ([]store.SignupsBySourceDataPoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSignupsBySource", ctx, campaignID, dateFrom, dateTo, period)
	ret0, _ := ret[0].([]store.SignupsBySourceDataPoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSignupsBySource indicates an expected call of GetSignupsBySource.
func (mr *MockAnalyticsStoreMockRecorder) GetSignupsBySource(ctx, campaignID, dateFrom, dateTo, period any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSignupsBySource", reflect.TypeOf((*MockAnalyticsStore)(nil).GetSignupsBySource), ctx, campaignID, dateFrom, dateTo, period)
}

// GetSignupsOverTime mocks base method.
func (m *MockAnalyticsStore) GetSignupsOverTime(ctx context.Context, campaignID uuid.UUID, dateFrom, dateTo time.Time, period string) ([]store.SignupsOverTimeDataPoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSignupsOverTime", ctx, campaignID, dateFrom, dateTo, period)
	ret0, _ := ret[0].([]store.SignupsOverTimeDataPoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSignupsOverTime indicates an expected call of GetSignupsOverTime.
func (mr *MockAnalyticsStoreMockRecorder) GetSignupsOverTime(ctx, campaignID, dateFrom, dateTo, period any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSignupsOverTime", reflect.TypeOf((*MockAnalyticsStore)(nil).GetSignupsOverTime), ctx, campaignID, dateFrom, dateTo, period)
}

// GetTopReferrers mocks base method.
func (m *MockAnalyticsStore) GetTopReferrers(ctx context.Context, campaignID uuid.UUID, limit int) ([]store.TopReferrerResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopReferrers", ctx, campaignID, limit)
	ret0, _ := ret[0].([]store.TopReferrerResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopReferrers indicates an expected call of GetTopReferrers.
func (mr *MockAnalyticsStoreMockRecorder) GetTopReferrers(ctx, campaignID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopReferrers", reflect.TypeOf((*MockAnalyticsStore)(nil).GetTopReferrers), ctx, campaignID, limit)
}

// GetUTMCampaignBreakdown mocks base method.
func (m *MockAnalyticsStore) GetUTMCampaignBreakdown(ctx context.Context, campaignID uuid.UUID, dateFrom, dateTo *time.Time) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUTMCampaignBreakdown", ctx, campaignID, dateFrom, dateTo)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUTMCampaignBreakdown indicates an expected call of GetUTMCampaignBreakdown.
func (mr *MockAnalyticsStoreMockRecorder) GetUTMCampaignBreakdown(ctx, campaignID, dateFrom, dateTo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUTMCampaignBreakdown", reflect.TypeOf((*MockAnalyticsStore)(nil).GetUTMCampaignBreakdown), ctx, campaignID, dateFrom, dateTo)
}

// GetUTMSourceBreakdown mocks base method.
func (m *MockAnalyticsStore) GetUTMSourceBreakdown(ctx context.Context, campaignID uuid.UUID, dateFrom, dateTo *time.Time) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUTMSourceBreakdown", ctx, campaignID, dateFrom, dateTo)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUTMSourceBreakdown indicates an expected call of GetUTMSourceBreakdown.
func (mr *MockAnalyticsStoreMockRecorder) GetUTMSourceBreakdown(ctx, campaignID, dateFrom, dateTo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUTMSourceBreakdown", reflect.TypeOf((*MockAnalyticsStore)(nil).GetUTMSourceBreakdown), ctx, campaignID, dateFrom, dateTo)
}
