// Code generated by MockGen. DO NOT EDIT.
// Source: processor.go
//
// Generated by this command:
//
//	mockgen -source=processor.go -destination=mocks_test.go -package=processor
//

// Package processor is a generated GoMock package.
package processor

import (
	store "base-server/internal/store"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockCampaignEmailTemplateStore is a mock of CampaignEmailTemplateStore interface.
type MockCampaignEmailTemplateStore struct {
	ctrl     *gomock.Controller
	recorder *MockCampaignEmailTemplateStoreMockRecorder
	isgomock struct{}
}

// MockCampaignEmailTemplateStoreMockRecorder is the mock recorder for MockCampaignEmailTemplateStore.
type MockCampaignEmailTemplateStoreMockRecorder struct {
	mock *MockCampaignEmailTemplateStore
}

// NewMockCampaignEmailTemplateStore creates a new mock instance.
func NewMockCampaignEmailTemplateStore(ctrl *gomock.Controller) *MockCampaignEmailTemplateStore {
	mock := &MockCampaignEmailTemplateStore{ctrl: ctrl}
	mock.recorder = &MockCampaignEmailTemplateStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCampaignEmailTemplateStore) EXPECT() *MockCampaignEmailTemplateStoreMockRecorder {
	return m.recorder
}

// CreateCampaignEmailTemplate mocks base method.
func (m *MockCampaignEmailTemplateStore) CreateCampaignEmailTemplate(ctx context.Context, params store.CreateCampaignEmailTemplateParams) (store.CampaignEmailTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCampaignEmailTemplate", ctx, params)
	ret0, _ := ret[0].(store.CampaignEmailTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCampaignEmailTemplate indicates an expected call of CreateCampaignEmailTemplate.
func (mr *MockCampaignEmailTemplateStoreMockRecorder) CreateCampaignEmailTemplate(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCampaignEmailTemplate", reflect.TypeOf((*MockCampaignEmailTemplateStore)(nil).CreateCampaignEmailTemplate), ctx, params)
}

// DeleteCampaignEmailTemplate mocks base method.
func (m *MockCampaignEmailTemplateStore) DeleteCampaignEmailTemplate(ctx context.Context, templateID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCampaignEmailTemplate", ctx, templateID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCampaignEmailTemplate indicates an expected call of DeleteCampaignEmailTemplate.
func (mr *MockCampaignEmailTemplateStoreMockRecorder) DeleteCampaignEmailTemplate(ctx, templateID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCampaignEmailTemplate", reflect.TypeOf((*MockCampaignEmailTemplateStore)(nil).DeleteCampaignEmailTemplate), ctx, templateID)
}

// GetCampaignByID mocks base method.
func (m *MockCampaignEmailTemplateStore) GetCampaignByID(ctx context.Context, campaignID uuid.UUID) (store.Campaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCampaignByID", ctx, campaignID)
	ret0, _ := ret[0].(store.Campaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCampaignByID indicates an expected call of GetCampaignByID.
func (mr *MockCampaignEmailTemplateStoreMockRecorder) GetCampaignByID(ctx, campaignID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCampaignByID", reflect.TypeOf((*MockCampaignEmailTemplateStore)(nil).GetCampaignByID), ctx, campaignID)
}

// GetCampaignEmailTemplateByID mocks base method.
func (m *MockCampaignEmailTemplateStore) GetCampaignEmailTemplateByID(ctx context.Context, templateID uuid.UUID) (store.CampaignEmailTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCampaignEmailTemplateByID", ctx, templateID)
	ret0, _ := ret[0].(store.CampaignEmailTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCampaignEmailTemplateByID indicates an expected call of GetCampaignEmailTemplateByID.
func (mr *MockCampaignEmailTemplateStoreMockRecorder) GetCampaignEmailTemplateByID(ctx, templateID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCampaignEmailTemplateByID", reflect.TypeOf((*MockCampaignEmailTemplateStore)(nil).GetCampaignEmailTemplateByID), ctx, templateID)
}

// GetCampaignEmailTemplatesByAccount mocks base method.
func (m *MockCampaignEmailTemplateStore) GetCampaignEmailTemplatesByAccount(ctx context.Context, accountID uuid.UUID) ([]store.CampaignEmailTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCampaignEmailTemplatesByAccount", ctx, accountID)
	ret0, _ := ret[0].([]store.CampaignEmailTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCampaignEmailTemplatesByAccount indicates an expected call of GetCampaignEmailTemplatesByAccount.
func (mr *MockCampaignEmailTemplateStoreMockRecorder) GetCampaignEmailTemplatesByAccount(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCampaignEmailTemplatesByAccount", reflect.TypeOf((*MockCampaignEmailTemplateStore)(nil).GetCampaignEmailTemplatesByAccount), ctx, accountID)
}

// GetCampaignEmailTemplatesByCampaign mocks base method.
func (m *MockCampaignEmailTemplateStore) GetCampaignEmailTemplatesByCampaign(ctx context.Context, campaignID uuid.UUID) ([]store.CampaignEmailTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCampaignEmailTemplatesByCampaign", ctx, campaignID)
	ret0, _ := ret[0].([]store.CampaignEmailTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCampaignEmailTemplatesByCampaign indicates an expected call of GetCampaignEmailTemplatesByCampaign.
func (mr *MockCampaignEmailTemplateStoreMockRecorder) GetCampaignEmailTemplatesByCampaign(ctx, campaignID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCampaignEmailTemplatesByCampaign", reflect.TypeOf((*MockCampaignEmailTemplateStore)(nil).GetCampaignEmailTemplatesByCampaign), ctx, campaignID)
}

// UpdateCampaignEmailTemplate mocks base method.
func (m *MockCampaignEmailTemplateStore) UpdateCampaignEmailTemplate(ctx context.Context, templateID uuid.UUID, params store.UpdateCampaignEmailTemplateParams) (store.CampaignEmailTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCampaignEmailTemplate", ctx, templateID, params)
	ret0, _ := ret[0].(store.CampaignEmailTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCampaignEmailTemplate indicates an expected call of UpdateCampaignEmailTemplate.
func (mr *MockCampaignEmailTemplateStoreMockRecorder) UpdateCampaignEmailTemplate(ctx, templateID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCampaignEmailTemplate", reflect.TypeOf((*MockCampaignEmailTemplateStore)(nil).UpdateCampaignEmailTemplate), ctx, templateID, params)
}

// MockEmailService is a mock of EmailService interface.
type MockEmailService struct {
	ctrl     *gomock.Controller
	recorder *MockEmailServiceMockRecorder
	isgomock struct{}
}

// MockEmailServiceMockRecorder is the mock recorder for MockEmailService.
type MockEmailServiceMockRecorder struct {
	mock *MockEmailService
}

// NewMockEmailService creates a new mock instance.
func NewMockEmailService(ctrl *gomock.Controller) *MockEmailService {
	mock := &MockEmailService{ctrl: ctrl}
	mock.recorder = &MockEmailServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailService) EXPECT() *MockEmailServiceMockRecorder {
	return m.recorder
}

// SendEmail mocks base method.
func (m *MockEmailService) SendEmail(ctx context.Context, to, subject, htmlContent string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEmail", ctx, to, subject, htmlContent)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendEmail indicates an expected call of SendEmail.
func (mr *MockEmailServiceMockRecorder) SendEmail(ctx, to, subject, htmlContent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmail", reflect.TypeOf((*MockEmailService)(nil).SendEmail), ctx, to, subject, htmlContent)
}
