// Code generated by MockGen. DO NOT EDIT.
// Source: internal/ai-capabilities/processor/new.go
//
// Generated by this command:
//
//	mockgen -source=internal/ai-capabilities/processor/new.go -destination=internal/ai-capabilities/processor/mocks_test.go -package=processor
//

// Package processor is a generated GoMock package.
package processor

import (
	store "base-server/internal/store"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAIStore is a mock of AIStore interface.
type MockAIStore struct {
	ctrl     *gomock.Controller
	recorder *MockAIStoreMockRecorder
	isgomock struct{}
}

// MockAIStoreMockRecorder is the mock recorder for MockAIStore.
type MockAIStoreMockRecorder struct {
	mock *MockAIStore
}

// NewMockAIStore creates a new mock instance.
func NewMockAIStore(ctrl *gomock.Controller) *MockAIStore {
	mock := &MockAIStore{ctrl: ctrl}
	mock.recorder = &MockAIStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAIStore) EXPECT() *MockAIStoreMockRecorder {
	return m.recorder
}

// CreateConversation mocks base method.
func (m *MockAIStore) CreateConversation(ctx context.Context, userID uuid.UUID) (*store.Conversation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateConversation", ctx, userID)
	ret0, _ := ret[0].(*store.Conversation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateConversation indicates an expected call of CreateConversation.
func (mr *MockAIStoreMockRecorder) CreateConversation(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateConversation", reflect.TypeOf((*MockAIStore)(nil).CreateConversation), ctx, userID)
}

// CreateMessage mocks base method.
func (m *MockAIStore) CreateMessage(ctx context.Context, conversationID uuid.UUID, role, content string) (*store.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMessage", ctx, conversationID, role, content)
	ret0, _ := ret[0].(*store.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMessage indicates an expected call of CreateMessage.
func (mr *MockAIStoreMockRecorder) CreateMessage(ctx, conversationID, role, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMessage", reflect.TypeOf((*MockAIStore)(nil).CreateMessage), ctx, conversationID, role, content)
}

// GetAllMessagesByConversationID mocks base method.
func (m *MockAIStore) GetAllMessagesByConversationID(ctx context.Context, conversationID uuid.UUID) ([]store.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllMessagesByConversationID", ctx, conversationID)
	ret0, _ := ret[0].([]store.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllMessagesByConversationID indicates an expected call of GetAllMessagesByConversationID.
func (mr *MockAIStoreMockRecorder) GetAllMessagesByConversationID(ctx, conversationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllMessagesByConversationID", reflect.TypeOf((*MockAIStore)(nil).GetAllMessagesByConversationID), ctx, conversationID)
}

// InsertUsageLog mocks base method.
func (m *MockAIStore) InsertUsageLog(ctx context.Context, usageLog store.UsageLog) (store.UsageLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertUsageLog", ctx, usageLog)
	ret0, _ := ret[0].(store.UsageLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertUsageLog indicates an expected call of InsertUsageLog.
func (mr *MockAIStoreMockRecorder) InsertUsageLog(ctx, usageLog any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertUsageLog", reflect.TypeOf((*MockAIStore)(nil).InsertUsageLog), ctx, usageLog)
}

// UpdateConversationTitleByConversationID mocks base method.
func (m *MockAIStore) UpdateConversationTitleByConversationID(ctx context.Context, conversationID uuid.UUID, title string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateConversationTitleByConversationID", ctx, conversationID, title)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateConversationTitleByConversationID indicates an expected call of UpdateConversationTitleByConversationID.
func (mr *MockAIStoreMockRecorder) UpdateConversationTitleByConversationID(ctx, conversationID, title any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConversationTitleByConversationID", reflect.TypeOf((*MockAIStore)(nil).UpdateConversationTitleByConversationID), ctx, conversationID, title)
}

// MockTextAIChatProcessor is a mock of TextAIChatProcessor interface.
type MockTextAIChatProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockTextAIChatProcessorMockRecorder
	isgomock struct{}
}

// MockTextAIChatProcessorMockRecorder is the mock recorder for MockTextAIChatProcessor.
type MockTextAIChatProcessorMockRecorder struct {
	mock *MockTextAIChatProcessor
}

// NewMockTextAIChatProcessor creates a new mock instance.
func NewMockTextAIChatProcessor(ctrl *gomock.Controller) *MockTextAIChatProcessor {
	mock := &MockTextAIChatProcessor{ctrl: ctrl}
	mock.recorder = &MockTextAIChatProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTextAIChatProcessor) EXPECT() *MockTextAIChatProcessorMockRecorder {
	return m.recorder
}

// ChatTextAI mocks base method.
func (m *MockTextAIChatProcessor) ChatTextAI(ctx context.Context, conversationID uuid.UUID, messages []store.Message) (<-chan StreamResponse, <-chan ModelResponse) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatTextAI", ctx, conversationID, messages)
	ret0, _ := ret[0].(<-chan StreamResponse)
	ret1, _ := ret[1].(<-chan ModelResponse)
	return ret0, ret1
}

// ChatTextAI indicates an expected call of ChatTextAI.
func (mr *MockTextAIChatProcessorMockRecorder) ChatTextAI(ctx, conversationID, messages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatTextAI", reflect.TypeOf((*MockTextAIChatProcessor)(nil).ChatTextAI), ctx, conversationID, messages)
}

// ContinueConversation mocks base method.
func (m *MockTextAIChatProcessor) ContinueConversation(ctx context.Context, userID, conversationID uuid.UUID, msg string) (<-chan StreamResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContinueConversation", ctx, userID, conversationID, msg)
	ret0, _ := ret[0].(<-chan StreamResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContinueConversation indicates an expected call of ContinueConversation.
func (mr *MockTextAIChatProcessorMockRecorder) ContinueConversation(ctx, userID, conversationID, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContinueConversation", reflect.TypeOf((*MockTextAIChatProcessor)(nil).ContinueConversation), ctx, userID, conversationID, msg)
}

// CreateConversation mocks base method.
func (m *MockTextAIChatProcessor) CreateConversation(ctx context.Context, userID uuid.UUID, msg string) (<-chan StreamResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateConversation", ctx, userID, msg)
	ret0, _ := ret[0].(<-chan StreamResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateConversation indicates an expected call of CreateConversation.
func (mr *MockTextAIChatProcessorMockRecorder) CreateConversation(ctx, userID, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateConversation", reflect.TypeOf((*MockTextAIChatProcessor)(nil).CreateConversation), ctx, userID, msg)
}
