// Code generated by MockGen. DO NOT EDIT.
// Source: processor.go
//
// Generated by this command:
//
//	mockgen -source=processor.go -destination=mocks_test.go -package=processor
//

// Package processor is a generated GoMock package.
package processor

import (
	store "base-server/internal/store"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockWebhookStore is a mock of WebhookStore interface.
type MockWebhookStore struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookStoreMockRecorder
	isgomock struct{}
}

// MockWebhookStoreMockRecorder is the mock recorder for MockWebhookStore.
type MockWebhookStoreMockRecorder struct {
	mock *MockWebhookStore
}

// NewMockWebhookStore creates a new mock instance.
func NewMockWebhookStore(ctrl *gomock.Controller) *MockWebhookStore {
	mock := &MockWebhookStore{ctrl: ctrl}
	mock.recorder = &MockWebhookStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookStore) EXPECT() *MockWebhookStoreMockRecorder {
	return m.recorder
}

// CreateWebhook mocks base method.
func (m *MockWebhookStore) CreateWebhook(ctx context.Context, params store.CreateWebhookParams) (store.Webhook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWebhook", ctx, params)
	ret0, _ := ret[0].(store.Webhook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWebhook indicates an expected call of CreateWebhook.
func (mr *MockWebhookStoreMockRecorder) CreateWebhook(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWebhook", reflect.TypeOf((*MockWebhookStore)(nil).CreateWebhook), ctx, params)
}

// DeleteWebhook mocks base method.
func (m *MockWebhookStore) DeleteWebhook(ctx context.Context, webhookID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWebhook", ctx, webhookID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWebhook indicates an expected call of DeleteWebhook.
func (mr *MockWebhookStoreMockRecorder) DeleteWebhook(ctx, webhookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWebhook", reflect.TypeOf((*MockWebhookStore)(nil).DeleteWebhook), ctx, webhookID)
}

// GetWebhookByID mocks base method.
func (m *MockWebhookStore) GetWebhookByID(ctx context.Context, webhookID uuid.UUID) (store.Webhook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWebhookByID", ctx, webhookID)
	ret0, _ := ret[0].(store.Webhook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWebhookByID indicates an expected call of GetWebhookByID.
func (mr *MockWebhookStoreMockRecorder) GetWebhookByID(ctx, webhookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebhookByID", reflect.TypeOf((*MockWebhookStore)(nil).GetWebhookByID), ctx, webhookID)
}

// GetWebhookDeliveriesByWebhook mocks base method.
func (m *MockWebhookStore) GetWebhookDeliveriesByWebhook(ctx context.Context, webhookID uuid.UUID, limit, offset int) ([]store.WebhookDelivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWebhookDeliveriesByWebhook", ctx, webhookID, limit, offset)
	ret0, _ := ret[0].([]store.WebhookDelivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWebhookDeliveriesByWebhook indicates an expected call of GetWebhookDeliveriesByWebhook.
func (mr *MockWebhookStoreMockRecorder) GetWebhookDeliveriesByWebhook(ctx, webhookID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebhookDeliveriesByWebhook", reflect.TypeOf((*MockWebhookStore)(nil).GetWebhookDeliveriesByWebhook), ctx, webhookID, limit, offset)
}

// GetWebhooksByAccount mocks base method.
func (m *MockWebhookStore) GetWebhooksByAccount(ctx context.Context, accountID uuid.UUID) ([]store.Webhook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWebhooksByAccount", ctx, accountID)
	ret0, _ := ret[0].([]store.Webhook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWebhooksByAccount indicates an expected call of GetWebhooksByAccount.
func (mr *MockWebhookStoreMockRecorder) GetWebhooksByAccount(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebhooksByAccount", reflect.TypeOf((*MockWebhookStore)(nil).GetWebhooksByAccount), ctx, accountID)
}

// GetWebhooksByCampaign mocks base method.
func (m *MockWebhookStore) GetWebhooksByCampaign(ctx context.Context, campaignID uuid.UUID) ([]store.Webhook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWebhooksByCampaign", ctx, campaignID)
	ret0, _ := ret[0].([]store.Webhook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWebhooksByCampaign indicates an expected call of GetWebhooksByCampaign.
func (mr *MockWebhookStoreMockRecorder) GetWebhooksByCampaign(ctx, campaignID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebhooksByCampaign", reflect.TypeOf((*MockWebhookStore)(nil).GetWebhooksByCampaign), ctx, campaignID)
}

// UpdateWebhook mocks base method.
func (m *MockWebhookStore) UpdateWebhook(ctx context.Context, webhookID uuid.UUID, params store.UpdateWebhookParams) (store.Webhook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWebhook", ctx, webhookID, params)
	ret0, _ := ret[0].(store.Webhook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWebhook indicates an expected call of UpdateWebhook.
func (mr *MockWebhookStoreMockRecorder) UpdateWebhook(ctx, webhookID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWebhook", reflect.TypeOf((*MockWebhookStore)(nil).UpdateWebhook), ctx, webhookID, params)
}

// MockWebhookService is a mock of WebhookService interface.
type MockWebhookService struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookServiceMockRecorder
	isgomock struct{}
}

// MockWebhookServiceMockRecorder is the mock recorder for MockWebhookService.
type MockWebhookServiceMockRecorder struct {
	mock *MockWebhookService
}

// NewMockWebhookService creates a new mock instance.
func NewMockWebhookService(ctrl *gomock.Controller) *MockWebhookService {
	mock := &MockWebhookService{ctrl: ctrl}
	mock.recorder = &MockWebhookServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookService) EXPECT() *MockWebhookServiceMockRecorder {
	return m.recorder
}

// TestWebhook mocks base method.
func (m *MockWebhookService) TestWebhook(ctx context.Context, webhookID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TestWebhook", ctx, webhookID)
	ret0, _ := ret[0].(error)
	return ret0
}

// TestWebhook indicates an expected call of TestWebhook.
func (mr *MockWebhookServiceMockRecorder) TestWebhook(ctx, webhookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TestWebhook", reflect.TypeOf((*MockWebhookService)(nil).TestWebhook), ctx, webhookID)
}
