// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks_test.go -package=service
//

// Package service is a generated GoMock package.
package service

import (
	store "base-server/internal/store"
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockWebhookStore is a mock of WebhookStore interface.
type MockWebhookStore struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookStoreMockRecorder
	isgomock struct{}
}

// MockWebhookStoreMockRecorder is the mock recorder for MockWebhookStore.
type MockWebhookStoreMockRecorder struct {
	mock *MockWebhookStore
}

// NewMockWebhookStore creates a new mock instance.
func NewMockWebhookStore(ctrl *gomock.Controller) *MockWebhookStore {
	mock := &MockWebhookStore{ctrl: ctrl}
	mock.recorder = &MockWebhookStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookStore) EXPECT() *MockWebhookStoreMockRecorder {
	return m.recorder
}

// CreateWebhookDelivery mocks base method.
func (m *MockWebhookStore) CreateWebhookDelivery(ctx context.Context, params store.CreateWebhookDeliveryParams) (store.WebhookDelivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWebhookDelivery", ctx, params)
	ret0, _ := ret[0].(store.WebhookDelivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWebhookDelivery indicates an expected call of CreateWebhookDelivery.
func (mr *MockWebhookStoreMockRecorder) CreateWebhookDelivery(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWebhookDelivery", reflect.TypeOf((*MockWebhookStore)(nil).CreateWebhookDelivery), ctx, params)
}

// GetPendingWebhookDeliveries mocks base method.
func (m *MockWebhookStore) GetPendingWebhookDeliveries(ctx context.Context, limit, maxAttempt int) ([]store.WebhookDelivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingWebhookDeliveries", ctx, limit, maxAttempt)
	ret0, _ := ret[0].([]store.WebhookDelivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingWebhookDeliveries indicates an expected call of GetPendingWebhookDeliveries.
func (mr *MockWebhookStoreMockRecorder) GetPendingWebhookDeliveries(ctx, limit, maxAttempt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingWebhookDeliveries", reflect.TypeOf((*MockWebhookStore)(nil).GetPendingWebhookDeliveries), ctx, limit, maxAttempt)
}

// GetWebhookByID mocks base method.
func (m *MockWebhookStore) GetWebhookByID(ctx context.Context, webhookID uuid.UUID) (store.Webhook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWebhookByID", ctx, webhookID)
	ret0, _ := ret[0].(store.Webhook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWebhookByID indicates an expected call of GetWebhookByID.
func (mr *MockWebhookStoreMockRecorder) GetWebhookByID(ctx, webhookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebhookByID", reflect.TypeOf((*MockWebhookStore)(nil).GetWebhookByID), ctx, webhookID)
}

// GetWebhooksByAccount mocks base method.
func (m *MockWebhookStore) GetWebhooksByAccount(ctx context.Context, accountID uuid.UUID) ([]store.Webhook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWebhooksByAccount", ctx, accountID)
	ret0, _ := ret[0].([]store.Webhook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWebhooksByAccount indicates an expected call of GetWebhooksByAccount.
func (mr *MockWebhookStoreMockRecorder) GetWebhooksByAccount(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebhooksByAccount", reflect.TypeOf((*MockWebhookStore)(nil).GetWebhooksByAccount), ctx, accountID)
}

// IncrementDeliveryAttempt mocks base method.
func (m *MockWebhookStore) IncrementDeliveryAttempt(ctx context.Context, deliveryID uuid.UUID, nextRetryAt *time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementDeliveryAttempt", ctx, deliveryID, nextRetryAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementDeliveryAttempt indicates an expected call of IncrementDeliveryAttempt.
func (mr *MockWebhookStoreMockRecorder) IncrementDeliveryAttempt(ctx, deliveryID, nextRetryAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementDeliveryAttempt", reflect.TypeOf((*MockWebhookStore)(nil).IncrementDeliveryAttempt), ctx, deliveryID, nextRetryAt)
}

// IncrementWebhookFailed mocks base method.
func (m *MockWebhookStore) IncrementWebhookFailed(ctx context.Context, webhookID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementWebhookFailed", ctx, webhookID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementWebhookFailed indicates an expected call of IncrementWebhookFailed.
func (mr *MockWebhookStoreMockRecorder) IncrementWebhookFailed(ctx, webhookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementWebhookFailed", reflect.TypeOf((*MockWebhookStore)(nil).IncrementWebhookFailed), ctx, webhookID)
}

// IncrementWebhookSent mocks base method.
func (m *MockWebhookStore) IncrementWebhookSent(ctx context.Context, webhookID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementWebhookSent", ctx, webhookID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementWebhookSent indicates an expected call of IncrementWebhookSent.
func (mr *MockWebhookStoreMockRecorder) IncrementWebhookSent(ctx, webhookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementWebhookSent", reflect.TypeOf((*MockWebhookStore)(nil).IncrementWebhookSent), ctx, webhookID)
}

// UpdateWebhookDeliveryStatus mocks base method.
func (m *MockWebhookStore) UpdateWebhookDeliveryStatus(ctx context.Context, deliveryID uuid.UUID, params store.UpdateWebhookDeliveryStatusParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWebhookDeliveryStatus", ctx, deliveryID, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWebhookDeliveryStatus indicates an expected call of UpdateWebhookDeliveryStatus.
func (mr *MockWebhookStoreMockRecorder) UpdateWebhookDeliveryStatus(ctx, deliveryID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWebhookDeliveryStatus", reflect.TypeOf((*MockWebhookStore)(nil).UpdateWebhookDeliveryStatus), ctx, deliveryID, params)
}
